= 想法

. 千万不要急着写代码，就像是"学骑自行车和学开飞机最有效的学习方法是不一样的"一个道理
.. 根据复杂程度，难度，熟悉程度的不同，有效的学习和实践方式不同
.. 体会: 引擎比后端难太多了!
. 设计思路和实现思路很可能差距很大，看源码逆推很可能是低效的，同时只知道原理就想写好同样也困难
.. 犯错：超前/过度学习，超前去看不适合自己的所谓最佳项目，过度想着打好基础再写都太低效
... 例子：过早去看PBRT4ed, 过早去看Filament引擎,过早去学vulkan，过早想着去封装vulkan底层
. 读源码也不是那么简单的，需要方法，技巧，和具备显性或硬性的前置知识和技能需求，具备不单指知不知道，还指程度深浅，有很多材料可不会显式的写明这些前置需求
.. 例：主要指的就是Filament，如果不是指只是看个大概的话还是很难的，因为虽然是轻量引擎，但是其是专家级的代码，很多思路和实现与之前学到，看到的很可能不同或者藏得深
.. 跟做英语阅读是一样的道理，英语水平直接影响阅读速度和理解程度，C++水平和图形/引擎工程水平，直接影响阅读速度和理解程度
. 很多公司或个人都喜欢对自己的产品，或者对自己自卖自夸，谨慎参考比如说明文档，相关材料等，不要轻信
.. 例子：很多博客，文章，网课，开源作品都有虚假宣传，浮夸的问题，要谨慎选择，选了以后的风险就是投入了时间，中途发现不对劲，不合适，不好，时间却花出去了
.. 但是不要轻易中途换资料，而是搞一个主线，然后找其他资料辅助参考，这种交叉比对学习法是有效的，这种方式应该用在comprehensive learning上，也就是需要深度阅读和学习的场景，一般集中在基础阶段
. 超前学习，过度设计, 过度工程化，过早优化的风险如影随形，需时刻警惕，就想走平衡木一样，要一步一步走，还需要时刻维持平衡
.. 例子：
... 过早考虑不用stl,总是想自己写
... 过早考虑细分很多模块，完全独立化
... 过早把架构搞得太复杂, 而且始终不定型，写代码时还老是纠结在架构合不合理上
... 过早想着引ECS,DOP
... 过早想着用vulkan的dynamic rendering
... 过早想着写render graph
.. 这些想法并不是不对，而是要从实际角度看，得容忍确实可能会有问题，但是项目得推得动，弄得自己推不动，理由再怎么正确也只剩理想上的意义了
.. 维持有一定空间演进就行
. 加要求和功能简单，裁剪才是更重要的
.. 例子：做着做着总感觉会不会做的太简单了，总感觉这里没完全弄懂，心里总是放不下，总想着回头补，但是项目推进怎么办？时间怎么办？
. 新不等于更好，可能只是老技术太成熟稳定，导致没优化空间了，不cool了，甚至团队没活了，而追新是有代价的
.. 新技术意味着例子少，意味着要为兼容一些老版本的库或代码想办法，很可能还搜不到解决办法，得自己来，无形加大了工作量
.. AI?对于网上资料少的问题你就试试吧，他会言之凿凿地天天忽悠你改这改那，最后发现根本不对，还得自己来
. 确实还是基础最重要，同时又难以速成，而且还得会练，就像当你举重30kg轻而易举的时候不加重很可能就不会继续进步了，也就是说，某种学习/行动方式很可能是存在瓶颈，局限性的
.. 你可能勉强自己可以举起一次100kg，但是并不是常态还可能伤身,同理，你可以勉强自己超前学习，硬着头皮学习，但是终归容易理解歪，效果又不好，即“走火入魔”
.. 从更大的范畴来说，我认为：在一个多因子互相影响的复杂系统中，改变单一因子带来的整体变化很可能都存在类似边际效益递减的效应
.. 但并不是说要从基础开始，从更务实更实践的角度来看，我认为应该是寻找一个合适的切入点，抓大放小，分阶段，演进式迭代
. 由自己的想法去演进，让别人的想法改进和补充自己的想法，自己的想法是主体
.. 例子：问这问那，却就是不问自己，总是过度担心自己想法可能不正确，有自己没意识到的问题
.. 不应该过度害怕写错，写不好，允许犯错，允许写起来"脏"一点，要知道，想使代码干净，和所谓高耦合低内聚都是有额外代价的，而不是应该过度追求的目标
... 并不是说不重视，而是说不应该过度，其中:
.... 高耦合低内聚：抽象分层高，类变多，代码量变大，维护起来麻烦，反而可能不灵活，为什么需要，主要是如果项目要大于5人且分模块各自开发时，这个追求才会更起作用，也就是说，这种思路主要是为中大型团队工程化考虑的，小型项目差不多就行，个人认为尽量保持依赖无环，薄和浅抽象，控制耦合度不要太高，代码量短小精悍即可
. 引擎真的不是一个项目，而是几个项目合成一块叫做"引擎",只要不是指那种"玩具引擎"
.. 正如卡马克所说：游戏引擎比造火箭可难多了
.. 但是我也认为，现在也确实比以前容易多了，而且也不算闭门造车，因为有大量不同水平和程度的开源代码和书籍参考，但是依旧需要裁剪，就如之前所说，加要求容易，裁剪才重要
.. 并不是否定玩具，相反，万丈高楼平地起，刚开始就是得从玩具开始
.. 也不是崇尚大型工程，相反，大型工程项目里，很可能100行代码里只有几行才是关键代码，剩下的很可能只是保证健壮性，安全性，调试，性能测试相关的代码，如果是为了学习原理和设计思想，去看大型项目很可能效率效果并不好
. 会说和会做真的是两码事，只能说二者具有一定相关性，而且相关程度视场景而定
.. 不要认为会说的人就会做，会做的人就会说
.. 二者都有技巧，都只是一种技能，是能学能会的
. 当你觉得网上教程铺天盖地的时候，真正实践起来才发现很多都是坑，而且大多数都是入门资料
.. 最常见问题包括但不限于：虚假宣传，虎头蛇尾，断联/断更，凌乱/散，不适配
. 没有完美的教程和书，作者/老师也是人，不要迷信书籍或教程，不要钻字眼里去，不要吹毛求疵，要懂读出精华，会寻找亮点，而且这些所谓"精华"真的对自己有用，别人觉得的"精华"不等于合适自己的精华
. 真正的原创想法远比"复读机式的人"少得多，但不能过度追求原创，得懂得鉴别和吸收，鉴别和吸收也不是说会就会的
.. 就如之前所说，在这个鉴别和吸收的过程中，容易出现的问题就是迷失主体或者说思想主体失焦
. 当很多人都说同样的话，不代表就是正确的，可能只是因为"三人市虎"
.. 当你了解的更多更深刻的时候，会发现能与别人有共鸣同感的点会变少，这并不意味着自己不正确，相反，可能确实是深刻多了，但是也需警惕走偏，走偏有时也有类似的现象，不一定能分辨
.. AI同样会受其影响
. 抄袭是一种诱惑，原创是困难且艰辛的，而且未必讨好，连讨好自己都未必
. AI总是假装自己很懂和很会写代码，然后真用起来就露馅，还总让人怀疑是自己没用好
.. 不是完全否定AI的作用，但是目前的AI明显存在不小的泡沫
... 我认为目前最有效的几种场景：翻译和总结，开阔设计和实现思路，写示例用的代码，辅助评审代码, 聊天消遣
... 写生产级代码，得强约束，和控制范围，目前我没发现很好的办法能稳定且保质输出，更别提代替(我倒是真希望它能让我坐在那抱着手看他写就行，是目前真的还不够稳定，不够好，至少我目前的开发领域和要求是如此)
... 写测试用例，我正想尝试
.. 警惕AI给出的建议，特别是你想要严肃对待的事，目前虽然每年都有进步，但是仍然无法避免误导和不适配
... 千万别听信网上推送的AI内容，目前主要因为几大科技巨头全部入场，宣传猛，而且AI刚开始接触时确实极具欺骗性
... 这种AI神教现象导致网上不太容许质疑，或者说质疑成本高，质疑者会被首先怀疑是自己不会用，反向否定甚至攻击质疑者，像极了教徒行为
... AI成了某些人的许愿机，或者满足某些人的心理，不需努力学习或者实践就能实现想法，成为了教徒们的精神纽带
... 推送算法直接绑定了特定群体，比如计算机领域，编程领域，只要你感兴趣，就给你狂推AI内容，是刻意的
... AI做别的不一定行，但是冒充真人灌水和虚假交流倒是可以的，要警惕网上那些评论和回复，有理由怀疑是假的
... 还有那些AI相关从业者，天天在网上骇人听闻，吹牛，少信，就如同说："我车库里有头大象,但是不给你看"
.. 但我觉得，整体上，AI确实让技术和知识的价值再一次贬值了，上一次恐怕是互联网的普及
. 当你试图进阶时，能找到的合适资料一下就少了很多，一方面是数量，一方面是适配，而且多数是英文资料
.. 如果不懂得从这些材料的表面中取其思想精粹，还有快速筛选的方法，真的是会越来越举步维艰
.. 越进阶能告诉你答案和路线的人或信息越少，每一步都像是试探而不再是像以前一样只需照着学/做就行了
.. 就如刻意练习里所说，找一个好的，合适的导师还是要更高效
... 自学者要解决的第一件事就是路线问题，还得自己亲自收集资料，和鉴别，AI只能算作其中一个信源，不要让其决定自己的路线，这就是之前提过的其中一种需要严肃对待的事
.... 搜索关键词:xxx roadmap, awesome xxx,xxx的教学大纲及其参考资料
..... 有很多人经历过的人可能分享过，用这个关键词来搜索，可能会发现高价值参考源，但是也不能盲信，因为可能也会有过时，或者其实作者自己也没实践，只是自己觉得不错就写上去了，或者很多山寨，高仿分享，又或者只是单纯在那里堆资料
.... 多交叉对比，多收集资料,可以先试学一下，再决定，磨刀不误砍柴工。
... 路线，思路问题造成的时间浪费更大还更隐蔽
... 路线的思路是： 要适配，要偏实践，很多路线的一大问题是理想化(先给你来几本大部头，要按那种路线走，很可能搞得几个月动不了手,而且后面学着就把前面的忘了)，就如之前所说，要找切入点，抓大放小，循序渐进，限制但容许犯错和偏差，实践为主(对于技术领域来说)。优质的确实有，但是很可能混在其中，需要精粹，蒸馏
... 但是要注意另一种问题：盲动主义，上来就干不重视原理不重视思想也不行的
.... 我觉得比较好的教学思路是当作师傅而不是老师，我认为计算机更多还是偏技术，偏实践的，真正研究计算机，而不是主要用它干活的人其实很少，应该是师徒模式比师生模式更好一些，前者偏实践(但是并不是说不重视理论)，后者偏理论
.... 我个人觉得计算机学科理论和实践的最佳比例是: 入门到高级之间时，都是3比7；然后高级水平到专家应该是4比6，专家及研究者需要理论才可能更高，比如:7比3，但是实践占比我认为最小不能小于3
.... 别怕学的多，真用得上的，远没有那么多，而且要一点一点来，所以说需要精粹，蒸馏
.... 学以致用大于学以致知
. 动静分离，多静少动: (优化思路)能编译期确定尽量编译期确定，缺点:编译期确定代码有时难写难读，运行时代码有时更好写好读
. 冷热分离，多冷少热: (优化思路)调用多的代码为热代码，少的为冷，让尽可能多的代码变为冷代码，同时让尽可能少的代码变为热代码
. 快慢分离，多快少慢: (优化思路)执行快的代码放在一起，慢的放在一起，让快的多执行，慢的代码执行频率尽量少
. 重复优于特例: (优化思路): 让代码执行时的流程统一(无状态)，利于做多线程，并行化，让代码运行时更快且好优化
. 特化快于通用： (优化心得): 特化的工具一般适用范围窄，但是优化上限高，泛化的工具则相反
. 确定性优先于灵活性: (设计心得): 系统执行时的状态在运行前就能推断出来，有利于调试和优化，但有时会不太灵活；灵活的代码容易在运行前不知道具体的状态，而且不好调试和优化，但是可能编写容易

== 说那么多，有什么用

衍生出几个心得总结主题

. 如何自学
. 如何阅读代码
. 如何开发引擎
. 如何用好AI
. 设计和优化心得