= 引擎架构

== 序言

=== 动机和期望

. 本项目是用来提升个人的{cpp}学习和工程实践能力的，而3D渲染引擎作为实时系统具有较为复杂和精巧的架构，是有挑战且有趣的项目
. 本项目的预期定位是中型引擎架构，且整体上希望超过大部分玩具级和教程级的项目，但是不会以大型工业级为目标
. 将采用独立自主设计和开发的方式，保证高度原创性，当前阶段暂不考虑AI辅助或生成
. 希望工程结构完整，现代, 易于管理
. 开发，测试，部署方便
. 设计思路清晰, 较为完整，文档解释清楚
. 代码质量好，易懂

=== 不应该做的事

. 过度工程化，比如:
.. 模块和分层拆的过细
.. 与项目不符的解耦和内聚的需求
.. 过早引入重型工具或库，采用过新的语言等级，编译器，过新的工具或库
. 过度设计, 比如:
.. 封装太多，抽象层次太高，鲁莽的自造或者引入新的抽象概念
.. 过度耦合或解耦
.. 与项目不符的健壮性，安全，封装，异常处理要求
.. 过度考虑性能问题
.. 高估未来可能性，过度考虑扩展性

=== 设计目标

现代3D实时渲染引擎

=== 应该完成的工作

. 设计和调研工作
* 引擎整体架构设计
* 引擎子系统设计
* 引擎工具链和库调研
. 开发工作
* 引擎项目构建方案和起始模板
* 引擎通用核心库
* 各个子模块的开发

== 1. 架构设计

我认为一款现代高级3d实时渲染引擎，最关键的几点应当包括:

. 架构上是有一定扩展性的，可演进的，能够避免后续大规模改动的问题，但把握好扩展性的度
. 采用现代但足够稳健的技术和API作为引擎依赖
.. 不能过度追新，可能导致缺乏软硬件支持，没有经过足够的实践考验，会有较高的踩坑风险
.. 要匹配项目目标和规模，冗余和过重的依赖会拖慢项目构建和编译过程
.. 不要的模块或库尽量别引入
.. 依赖尽量少，依赖链尽量短
.. 用起来顺手，好用
.. 不要偏信库的文档材料，先试用
.. 有文档，使用者较多，用户反馈总体还不错
.. 最好源码易读能改，开源协议合适等
. 易于调试，易于追踪性能，方便后续测试和优化
. 构建和部署方便，方案现代
. 为了充分发挥硬件性能，系统应采用多线程方式执行，尽量使执行能够并行化，支持异步，比如资源处理，渲染指令处理，场景数据处理等
. api容易使用，代码易于理解，设计尽量符合直觉, 减少学习成本

=== 1.1 层次与模块

* 引擎整体逻辑上为分层架构，每个层级相当于一个子系统，子系统内部有自己的子架构，每个层级(子系统)拥有多个模块
* 平台层放在引擎内部统一处理，平台在构建时按不同平台架构按需引入，平台层也提供了窗口系统封装，引擎为跨平台运行提供扩展性，不需要外部处理平台差异，基本实现开箱即用
* 渲染底层(后端)和平台层在构建时确定，采用编译时绑定，不支持(也没必要)运行时多态
* 模块在构建时静态连接作为一个整体引擎核心库，核心库部分不支持动态链接
* 实际代码会基于此架构实现，但不一定与文档所述完全一致，以系统设计文档和实际代码为准
* 具体设计见系统设计文档和模块设计文档

. 平台层: 负责处理平台相关的功能，比如：操作系统, 文件系统, 输入系统，窗口系统等
.. 文件系统模块: 文件读写接口抽象，负责各种介质文件的读写，比如硬盘介质等
.. 窗口系统模块: 负责系统创建和管理可渲染窗口接口，预留不同窗口的扩展性
.. 操作系统模块: 按操作系统来区分，可在内部组合需要的文件系统，窗口系统等
. 核心层: 全局通用工具, 基类，配置类等
.. 工具模块: 自定义容器,便利功能，内存分配等
.. 通用模块：异常处理, 配置，调试器，通用基类等
.. 数学模块: 数学相关的功能
. 资产层: 负责读取各种资产文件，解析并转换为引擎内部统一的数据格式，方便引擎使用
.. 解析器模块： 负责不同文件格式资产的解析，转换为引擎内部数据格式
.. 编译器模块: 负责资产转换前或转换后的额外操作，比如纹理压缩，mesh优化等
. 资源层: 负责运行时资源的管理，包括CPU和GPU侧资源的调度，生命周期管理
. 渲染前端层: 负责定义和执行具体的渲染流水线，也包括材质系统，效果，gui等
.. 材质管理模块: 材质模板，材质实例，材质缓存等
.. 着色器管理模块: 着色器编译，着色器缓存等
.. render graph模块: 渲染图管理，渲染管线编排，剔除，自动屏障等
. 渲染后端层: 负责底层图形API的统一化封装(RHI)，为渲染前端提供基础能力
.. vulkan模块: vulkan实现的渲染后端
. 场景层: 负责管理场景相关数据，包括：场景描述接口，场景图，相机，视图等
. 应用层: 通用资源操作逻辑和引擎常用功能封装，方便使用者使用引擎

=== 1.2 核心调用链

本引擎的架构是以工业级引擎的架构作为参考，并且结合实际情况做了精简和提炼，根据个人理解和重新整合，最终形成了本架构设计

此处说明引擎核心架构和流程，实际调用链基于此流程但不一定完全一致，以系统设计文档和代码为准

[NOTE]
====
* 为了简化表述，此图未说明多线程和异步过程
* 只有架构高层级模块和核心步骤，子系统具体调用步骤参考系统设计和模块设计文档
* Engine区别于其他模块，其不是一个平级概念，而是一个顶层协调者，具体执行逻辑由各个子系统负责
* Application是独立模块，只依赖整个引擎库
* 资源，资产，场景数据处理会委托job system的独立线程完成任务
* 主线程与后端线程独立,主线程只管理全局统筹相关事务，执行main loop,录制渲染命令，后端线程只处理渲染底层逻辑
* 具体技术细节此处不赘述，详见系统设计及模块设计文档
====

[plantuml]
....
actor developer as User
group 构造
    User -> Application++: new App()
    Application -> Engine++: new Engine()
    Engine -> Engine: init common services(logger, arena, job system, etc)
    Engine -> Platform++: platform.init()
    Platform -> Platform: init FileSystem
    Platform -> Platform: init WindowSystem
    Engine <-- Platform: platform init finished
    Engine -> Backend++: new
    Engine -> ResourceManager++: new
    Engine -> AssetManager++: new
    Engine -> SceneManager++: new
    Engine -> Renderer++: new
    Application <-- Engine: engine construction finished
    User <-- Application: App construction finished
end
group 初始化
    User -> Application: init()
    Application -> Engine: init()
    Engine -> Platform: new window
    Engine -> Backend: init()
    Engine -> ResourceManager: init()
    Engine -> AssetManager: init()
    Engine -> SceneManager: init()
    Engine -> Renderer: init()
    Application <-- Engine: engine init finished
    User <-- Application: app init finished
end
group 运行
    User -> Application: run()
    Application -> Engine: run()
    Engine -> SceneManager: load scene
    SceneManager -> AssetManager: load asset
    AssetManager -> AssetManager: load file, convert file to Asset data
    SceneManager <-- AssetManager: finished asset file loading & parsing
    SceneManager -> ResourceManager: register assets
    SceneManager -> SceneManager: build scene data 
    SceneManager -> ResourceManager: load resources
    ResourceManager -> Backend: load registered backend resources
    Engine <-- SceneManager: finished scene loading
    loop
        Engine -> Platform: poll events and execute callbacks
        Engine -> SceneManager: update scene data
        Engine -> Renderer: begin rendering
        Renderer -> Renderer: prepare rendering context data
        Renderer -> Backend: new render frame
        Backend -> Backend: acquire next swapchain image, prepare frame data
        Renderer <-- Backend: new frame ready
        Renderer -> Renderer: render graph setup, compile, execute
        Renderer -> Backend: submit recorded rendering commands
        Backend -> Backend: execute commands
        Renderer -> Backend: end frame
        Backend -> Backend: end commands, end rendering, present etc.
        Renderer <-- Backend: ended frame
        Renderer -> ResourceManager: update deletion queue
    end
end
group 用户停止或停止事件触发
    User -> Application: stop() or engine stop event triggered
    Application -> Engine: stop()
    Engine -> Engine: wait job system idle
    Engine -> Platform: stop event
    Engine -> Renderer: stop rendering
    Renderer -> Backend: wait idle
    Engine <-- Renderer: finished renderer stop
    Engine -> SceneManager: unload scene
    SceneManager -> SceneManager: clear scene data, reset status
    SceneManager -> ResourceManager: unload resources
    ResourceManager -> ResourceManager: unload scene resources
    ResourceManager -> Backend: unload backend resources
    Engine <-- SceneManager: finished stop scene
    Application <-- Engine: finished engine stop
    User <-- Application: finished app stop
end
group 销毁
    User -> Application: delete App
    Application -> Engine: destroy()
    Engine -> Renderer: destroy()
    deactivate Renderer
    Engine -> SceneManager: destroy()
    deactivate SceneManager
    Engine -> AssetManager: destroy()
    deactivate AssetManager
    Engine -> ResourceManager: destroy()
    deactivate ResourceManager
    Engine -> Backend: destroy()
    deactivate Backend
    Engine -> Platform: destroy()
    deactivate Platform
    Engine -> Engine: destroy common services
    Application <-- Engine: finished engine destroy
    Application -> Engine: delete engine
    deactivate Engine
    User <-- Application: finished app delete
    deactivate Application
end
....

== 2. 暂时不做的功能

. 完整的RHI: 会预留RHI层抽象，但目前不会实现多后端，只有vulkan后端，预留了可扩展性
. 完整的跨平台能力: 但会预留平台层抽象，并预留跨平台构建和配置的能力
. 完整的编辑器: 暂不完成，包括运行时反射功能
. AI辅助编程: 由于需要同时保证学习目的和技术真实水平，保持完整独立的原创性, 此阶段暂不引入
. 脚本系统: 暂不支持，但提供C++接口，和Application封装，可直接使用引擎提供的接口和{cpp}开发具体应用


=== 3. 技术选型

所有库的依赖以满足需求的前提下，优先选轻薄，易用，依赖少，相对成熟的库，目前阶段避免：大而全、不上不下、过时、或不够成熟的库

三方库调研过程主要是个人调研，原则是契合项目情况，会参考项目issues，用户反馈意见，较现代，偏稳健，不激进，个人试用感觉可接受，顺手，构建简单，调研过程略

三方库中的类型如果广泛使用，会封装成引擎内部类型，保证三方库的类型不强耦合在引擎中，尽量实现可插拔能力，但是考虑实现成本，务实执行，不强制

==== 对"高级现代C++图形"需求的实现

. 本项目定位是介于教学级和工业级引擎之间，参考现代引擎架构来进行设计和实现
. 采用C++23作为主要编程语言，会使用的新特性包括
.. concept: 用于约束模板类型
.. designated initializer: 用于方便的在构造结构体时确定参数
.. expected: 配合引擎错误码封装和异常管理策略，实现API错误可控，性能较好，避免异常传播和滥用
.. 基于C++23实现的核心基础类，工具类
. 采用RHI层屏蔽渲染后端API差异，采用vulkan1.3作为当前版本的主要渲染后端
.. Vulkan支持dynamic rendering, bindless
.. shader语言为Slang
.. 支持运行时编译着色器
.. 支持渲染指令多线程录制
.. 采用render graph实现渲染管线

==== 三方库使用简述

. 数学库: 基于glm封装
. 标准库: 帧外部分允许使用{cpp} STL, 帧内部分和热路径使用自研容器或三方库容器，使用自定义分配器手动管理资源，详见系统设计
. 内存管理: 自研Arena内存分配器
. 窗口系统: 基于SDL3封装，实现了引擎窗口系统接口
. ECS: 基于EnTT封装，主要用于实现数据驱动的场景管理
. job system: 基于taskflow开发，主要用于异步多线程场景数据处理
. gltf加载: 基于fastgltf封装,用于读取和解析gltf文件
. vulkan底层封装: 采用vulkan-headers, vulkan-utility, vma, volk, spirv-reflect, slangc，并自行封装，实现渲染后端(RHI)接口
. 测试/调试: Catch2, RenderDoc, Tracy，基于imgui提供性能剖析，调试可视化

==== 对"易于开发, 维护, 扩展, 部署"需求的实现

. 采用Git + CMake + vcpkg实现版本管理，模块化构建，三方库管理,需要定制的三方库代码会在本地vendor文件夹中，提供跨平台部署和扩展的扩展性
. 采用clang-format + clang-tidy实现代码格式，代码基本质量的管理

==== 对"易于测试"需求的实现

. 采用Catch2实现测试功能，由于人力有限，目前以保证核心功能点正常运行为主
. 提供基本功能的单元测试用例，和引擎使用样例

==== 对"易于调试"需求的实现

. 采用Vulkan验证层 + RenderDoc + Tracy，并在核心库配套debug, profiler, log工具，对引擎功能有监控测量的能力
. 集成日志，断言，和调试工具

==== 对"易于理解"需求的实现

. 采用doxygen+doxybook2+mkdocs工具链方案，且类/主要函数都有注释，并配有设计文档，尽量简明扼要，通俗易懂
. 采用asciidoc整理整体文档(注：推荐使用vscode配合asciidoctor插件并打开kroki预览功能以获得最佳体验)
. 引擎会采用版本逐步迭代的方式推进，从最简实现逐步复杂化，会对每个大阶段以tag存档，方便回查

== 局限

. 由于人力有限，无法充分测试
. 只保证核心流程，不保证测试覆盖，文档覆盖

== 开发策略

. semantic compression思想, 即link:https://caseymuratori.com/blog_0015[语义压缩]，推荐阅读
. 提前做设计是十分必要的，但是不过度考虑设计和优化问题，优化的前提是发现有性能问题，然后测量，发现主要瓶颈，再解决瓶颈
. 设计定稿后，非必要不再修改和重新思考设计问题
. 全程保证项目可以成功构建，跑通
. 先定项目的骨架代码，按模块顺序设计和开发

=== 附录

==== 参考资料

. 架构设计相关
.. Game Engine Architecture
.. Clean Architecture
.. vulkan.org - building a Simple Engine
.. game programming patterns
.. Google - Filament
.. KDAP - KDGpu
.. NVIDIA - NvRHI

. 技术相关
.. {cpp} core guideline
.. modern CMake for {cpp}
.. real time rendering
.. vkguide.dev - vulkan guide
.. vulkan programming guide
.. vulkan cookbook
.. modern vulkan cookbook
.. mastering graphics programming with vulkan
.. howtovulkan.com by Sascha Willems
.. vulkan samples by Sascha Willems
.. siggraph 2026 - vk tutorial

还有许多参考资料，由于没有一一记录，此处略