= 引擎架构

== 设计目标

一个高级现代3D实时图形渲染引擎，本项目需要易于开发，维护，扩展，调试，测试，部署，理解，使用

== 关键指导思想

. KISS: 设计和实现简单，易于理解
. YAGNI: 不高估未来的需求，避免过度设计，过度工程化，过早优化
. SOLID: 高内聚、低耦合，多扩展少修改, 用抽象建立契约, 接口和实现分离，慎重引入依赖，依赖倒置
. EA: 演进式架构，基于版本稳步演进

务实执行上述思想，不教条，使用工具和开发规约保障基本底线，平衡开发效率和质量

== 开发目标

. 完全自主设计和研发，只参考，不抄袭，保证高度原创，暂不引入AI
. 代码质量良好: 由工具和文档规约保障
. 代码易于测试: 为了平衡单人开发效率，有关键功能的简单测试，并保证通过
. 代码易于理解：现阶段以体现设计思路，完成功能为主，由注释和文档保障易理解，尽量减少代码量和高层次抽象，
. 代码易于调试: 主要由日志，调试工具，和可视化窗口保障

对于扩展性和健壮性，会在设计时基于具体场景进行权衡，一般来说会在代码基座和骨架层面做铺底，但不过度

=== 运行时目标

. 引擎: 各个核心组件正常，生命周期可追踪、无内存泄漏，测试用例通过
. 线程功能: 保证线程安全, 执行正确，生命周期可追踪
. 渲染功能: 渲染Pass的执行顺序、资源屏障, 同步机制正确。无显存越界、无验证层报错、无画面闪烁等其他明显的显示问题
. 资源加载: 运行时无卡死报错

=== 部署时目标

. 解压即部署
. 暂只考虑windows平台部署，但预留跨平台构建和部署空间

=== 应该实现的关键功能点

包含的功能点包括：

. 引擎基础工具类: 包括自定义容器，内存管理，调试，性能追踪，剖析器，架构模式，设计模式基类，其他工具类
. 多线程: job system
. 资源管理: 离线与运行时资源处理分离，资源文件读写，解析，转换，加载，销毁等
. 平台层：预留跨平台接口，窗口系统，跨渲染底层扩展能力
. 场景管理: 数据驱动，属性中心架构，与资源系统，渲染系统解耦
. 测试用例: 核心功能提供测试用例
. 引擎使用示例: 会提供合适的使用示例，展示核心功能和使用方法
. vulkan底层封装: 自研图形底层封装，自研RHI，但是目前会以贴近vulkan实现为主
. 着色器功能: 支持slang运行时编译，热加载
. render graph: 支持自定义pass，支持forward, deferred等着色方式， 自动生命周期管理，自动屏障等
. 渲染技术: 支持PBR渲染

=== 暂不考虑的功能

. 完整的RHI: 会预留RHI层抽象，但目前不会实现多后端，只有vulkan后端，预留了可扩展性
. 完整的跨平台能力: 但会预留平台层抽象，并预留跨平台构建和配置的能力
. 完整的编辑器: 暂不完成，包括运行时反射功能
. AI辅助编程: 由于需要同时保证学习目的和技术真实水平，保持完整独立的原创性, 此阶段暂不引入
. 脚本系统: 暂不支持，但提供C++接口，和Application封装，可直接使用引擎提供的接口和{cpp}开发具体应用

== 架构及核心调用链

本引擎的架构是以工业级引擎的架构作为参考，并且结合实际情况做了精简和提炼，根据个人理解和重新整合，最终形成了本架构的设计

=== 层级及模块划分介绍

* 引擎整体逻辑上为分层架构，每个层级相当于一个子系统，子系统内部有自己的子架构，每个层级(子系统)拥有多个模块
* 平台层放在引擎内部统一处理，平台在构建时按不同平台架构按需引入，平台层也提供了窗口系统封装，引擎为跨平台运行提供扩展性，不需要外部处理平台差异，基本实现开箱即用
* 渲染底层(后端)和平台层在构建时确定，采用编译时绑定，不支持(也没必要)运行时多态
* 模块在构建时静态连接作为一个整体引擎核心库，核心库部分不支持动态链接
* 实际代码会基于此架构实现，但不一定与文档所述完全一致，以系统设计文档和实际代码为准
* 具体设计见系统设计文档和模块设计文档

. 平台层: 平台相关底层封装，包括：操作系统, 文件系统, 输入系统，窗口系统等
. 核心层: 工具类, 架构基类，全局配置类等，比如: 日志，数学库，profiler, 配置，反射，序列化, 内存管理, 自定义容器等
. 资产层: 负责读取各种资产文件，解析并转换为引擎内部格式的数据
. 资源层: 负责运行时资源的管理，包括GPU侧资源的加载，卸载时机
. 渲染层(前端): 负责定义和执行具体的渲染流水线，也包括材质系统，效果，gui等
. 渲染层(后端): 负责底层图形API封装和资源管理，为渲染前端提供基础能力
. 场景层: 负责管理场景相关数据，包括：场景描述接口，场景图，相机等
. 应用层: 通用资源操作逻辑和引擎常用功能封装，方便引擎使用

=== 引擎架构及核心流程

此处说明引擎核心架构和流程，实际调用链基于此流程但不一定完全一致，以系统设计文档和代码为准

[NOTE]
====
* 为了简化表述，此图未说明多线程和异步过程
* 只有架构高层级模块和核心步骤，子系统具体调用步骤参考系统设计和模块设计文档
* Engine区别于其他模块，其不是一个平级概念，而是一个顶层协调者，具体执行逻辑由各个子系统负责
* Application是独立模块，只依赖整个引擎库
* 资源，资产，场景数据处理会委托job system的独立线程完成任务
* 主线程与后端线程独立,主线程只管理全局统筹相关事务，执行main loop,录制渲染命令，后端线程只处理渲染底层逻辑
* 具体技术细节此处不赘述，详见系统设计及模块设计文档
====

[plantuml]
....
actor developer as User
group 构造
    User -> Application++: new App()
    Application -> Engine++: new Engine()
    Engine -> Engine: init common services(logger, arena, job system, etc)
    Engine -> Platform++: platform.init()
    Platform -> Platform: init FileSystem
    Platform -> Platform: init WindowSystem
    Engine <-- Platform: platform init finished
    Engine -> Backend++: new
    Engine -> ResourceManager++: new
    Engine -> AssetManager++: new
    Engine -> SceneManager++: new
    Engine -> Renderer++: new
    Application <-- Engine: engine construction finished
    User <-- Application: App construction finished
end
group 初始化
    User -> Application: init()
    Application -> Engine: init()
    Engine -> Platform: new window
    Engine -> Backend: init()
    Engine -> ResourceManager: init()
    Engine -> AssetManager: init()
    Engine -> SceneManager: init()
    Engine -> Renderer: init()
    Application <-- Engine: engine init finished
    User <-- Application: app init finished
end
group 运行
    User -> Application: run()
    Application -> Engine: run()
    Engine -> SceneManager: load scene
    SceneManager -> AssetManager: load asset
    AssetManager -> AssetManager: load file, convert file to Asset data
    SceneManager <-- AssetManager: finished asset file loading & parsing
    SceneManager -> ResourceManager: register assets
    SceneManager -> SceneManager: build scene data 
    SceneManager -> ResourceManager: load resources
    ResourceManager -> Backend: load registered backend resources
    Engine <-- SceneManager: finished scene loading
    loop
        Engine -> Platform: poll events and execute callbacks
        Engine -> SceneManager: update scene data
        Engine -> Renderer: begin rendering
        Renderer -> Renderer: prepare rendering context data
        Renderer -> Backend: new render frame
        Backend -> Backend: acquire next swapchain image, prepare frame data
        Renderer <-- Backend: new frame ready
        Renderer -> Renderer: render graph setup, compile, execute
        Renderer -> Backend: submit recorded rendering commands
        Backend -> Backend: execute commands
        Renderer -> Backend: end frame
        Backend -> Backend: end commands, end rendering, present etc.
        Renderer <-- Backend: ended frame
        Renderer -> ResourceManager: update deletion queue
    end
end
group 用户停止或停止事件触发
    User -> Application: stop() or engine stop event triggered
    Application -> Engine: stop()
    Engine -> Engine: wait job system idle
    Engine -> Platform: stop event
    Engine -> Renderer: stop rendering
    Renderer -> Backend: wait idle
    Engine <-- Renderer: finished renderer stop
    Engine -> SceneManager: unload scene
    SceneManager -> SceneManager: clear scene data, reset status
    SceneManager -> ResourceManager: unload resources
    ResourceManager -> ResourceManager: unload scene resources
    ResourceManager -> Backend: unload backend resources
    Engine <-- SceneManager: finished stop scene
    Application <-- Engine: finished engine stop
    User <-- Application: finished app stop
end
group 销毁
    User -> Application: delete App
    Application -> Engine: destroy()
    Engine -> Renderer: destroy()
    deactivate Renderer
    Engine -> SceneManager: destroy()
    deactivate SceneManager
    Engine -> AssetManager: destroy()
    deactivate AssetManager
    Engine -> ResourceManager: destroy()
    deactivate ResourceManager
    Engine -> Backend: destroy()
    deactivate Backend
    Engine -> Platform: destroy()
    deactivate Platform
    Engine -> Engine: destroy common services
    Application <-- Engine: finished engine destroy
    Application -> Engine: delete engine
    deactivate Engine
    User <-- Application: finished app delete
    deactivate Application
end
....

=== 技术选型

所有库的依赖以满足需求的前提下，优先选轻薄，易用，依赖少，相对成熟的库，目前阶段避免：大而全、不上不下、过时、或不够成熟的库

三方库调研过程主要是个人调研，原则是契合上述要求，会参考项目issues，用户反馈意见，较现代，偏稳健，不激进，个人试用感觉可接受，顺手，构建简单，调研过程略

三方库中的类型如果广泛使用，会封装成引擎内部类型，保证三方库的类型不强耦合在引擎中，尽量实现可插拔能力，但是考虑实现成本，务实执行，不强制

==== 对"高级现代C++图形"需求的实现

. 采用C++23作为主要编程语言，会使用的新特性包括
.. concept: 用于约束模板类型
.. designated init: 用于方便的在构造时确定参数
.. expected: 代替错误码，不使用异常，性能更好且易读
.. 基于C++23的核心基础类，工具类
. 采用RHI层屏蔽渲染后端API差异，采用vulkan1.3作为当前版本的主要渲染后端
.. Vulkan支持dynamic rendering, bindless
.. shader语言为Slang
.. 支持渲染指令异步录制
.. 驱动线程主线程分离架构
.. 三方库
... 数学库: 基于glm封装
... 标准库: 帧外部分允许使用{cpp} STL, 帧内部分和热路径使用自研容器或三方库容器，使用自定义分配器手动管理资源，详见系统设计
... 内存管理: 自研Arena内存分配器
... 窗口系统: 基于SDL3封装，并预留WSI接口，方便未来扩展
... ECS: 基于EnTT封装，主要用于实现DOD场景管理
... job system: 基于EnkiTS开发，主要用于异步多线程场景数据处理
... gltf加载: 基于fastgltf封装,用于读取和解析gltf文件
... 纹理读取和转换: 基于stb和libktx封装
... 文件读写：基于stl filesystem封装并预留接口提供扩展性
... vulkan底层封装: 自研，采用vulkan-headers, vulkan-utility, vma, volk, spirv-reflect, slangc
... 测试/调试: Catch2, RenderDoc, Tracy，基于imgui提供性能剖析，调试可视化

==== 对"易于开发, 维护, 扩展, 部署"需求的实现

. 采用Git + CMake + vcpkg实现版本管理，模块化构建，三方库管理,需要定制的三方库代码会在本地vendor文件夹中，提供跨平台部署和扩展的扩展性
. 采用clang-format + clang-tidy实现代码格式，代码质量的管理

==== 对"易于测试"需求的实现

. 采用Catch2实现测试功能，由于人力有限，目前以保证核心功能点正常运行为主
. 提供基本功能的单元测试用例，和引擎使用样例

==== 对"易于调试"需求的实现

. 采用Vulkan验证层 + RenderDoc + Tracy，并在核心库配套debug, profiler, log工具，对引擎功能有监控测量的能力
. 集成日志，断言，和调试工具

==== 对"易于理解"需求的实现

. 采用doxygen+doxybook2+mkdocs工具链方案，且类/主要函数都有注释，并有丰富的文档，保证简明扼要，通俗易懂，尽量不堆砌高概念和专业辞藻
. 采用asciidoc整理整体文档(注：推荐使用vscode配合asciidoctor插件并打开kroki预览功能以获得最佳体验)
. 代码的追求是: 用最简洁的代码充分表达设计和思路，在满足目标的前提下，尽量避免过度工程化，过度设计
. 引擎会采用版本逐步迭代的方式推进，从最简实现逐步复杂化，会对每个大阶段以tag存档，方便回查

== 局限

. 由于人力有限，无法充分测试

== 开发策略

. 务实
. semantic compression思想, 即link:https://caseymuratori.com/blog_0015[语义压缩]，推荐阅读
. 提前做设计是十分必要的，但是不过度考虑设计和优化问题，优化的前提是发现有性能问题，然后测量，发现主要瓶颈，再解决瓶颈
. 设计定稿后，非必要不再三番五次修改和重新思考设计问题
. 全程保证项目可以成功构建，跑通
. 先定项目的骨架代码，再写具体代码
. 模块应该基本完成后，再写其他模块

=== 附录

==== 参考资料

. 架构设计相关
.. Game Engine Architecture
.. Clean Architecture
.. vulkan.org - building a Simple Engine
.. game programming patterns
.. Google - Filament
.. KDAP - KDGpu
.. NVIDIA - NvRHI

. 技术相关
.. {cpp} core guideline
.. modern CMake for {cpp}
.. real time rendering
.. vkguide.dev - vulkan guide
.. vulkan programming guide
.. vulkan cookbook
.. modern vulkan cookbook
.. mastering graphics programming with vulkan
.. howtovulkan.com by Sascha Willems
.. vulkan samples by Sascha Willems
.. siggraph 2026 - vk tutorial

还有许多参考资料，由于没有一一记录，此处略