= 模块设计简述

== core模块

=== 内存管理

==== 职责

引擎底层内存管理相关功能，应该有多种分配算法，包括：

* pool: 用于支持对象池
* linear: 线性分配，用于帧内快速分配和清除
* heap: 堆分配，用于动态创建的内存对象
* 支持未来扩展，如stack分配，double linear分配等

* 应该可支持调试，支持分配和销毁时的自定义逻辑
* 应该可支持线程安全，分配时对齐
* 可作为容器的分配器，如stl分配器
* 高性能

==== 本版边界

* 不实现跨平台，但预留扩展

==== 设计思路

采用policy-based 模板类实现，单头文件，详见doxygen文档和代码

=== 事件系统

==== 职责

==== 设计思路

== 资产/资源管理模块

资源管理可以说是整个引擎的大动脉，是必须清晰整理数据流，逻辑流，状态流的模块

=== 职责

. 从硬盘里读取文件，解析，转换，生成引擎内部资产
. 在引擎运行时，使用这些数据进行处理和渲染

=== 功能

. 文件读取和解析: 应包括gltf2.0形式的文件和ktx纹理文件，解析为对应数据结构
.. 复合资产文件：比如gltf解析，并分解成单个资产，比如material, mesh, texture, buffer, scene等
. 文件转换
.. 优化数据结构：比如mesh, texture，buffer等，在转换时可以优化为引擎内部字节流
.. 把gltf和ktx转为引擎内部的PdMesh, PdTexture, PdSceneGraph, PdBuffer等数据结构
. 运行时加载和资源生命周期管理: 把上述引擎内数据在引擎运行时加载到内存和GPU并控制其构造和销毁时机

=== 本版边界

. 实现gltf和ktx的读取，解析，转换，运行时加载，正确渲染
. 不实现gltf的蒙皮，动作，多场景解析
. 不实现异步多线程加载,但是预留扩展性
. 不实现流式加载，热重载，但是预留扩展性
. 不实现gltf导出，修改

=== 设计思路

. 资源的加载整体上分为两块，资产管理和资源管理,此处分别称为(Asset Management(AM)和Resource Management(RM))
.. AM: 负责硬盘文件信息读取，并解析转换为运行时资源信息，本身不负责直接加载数据，只解析和转换相关文件的信息，并提供把转换好的资产"注册"到运行时资源管理中
.. RM: 利用资产管理解析的文件信息，在运行时按照场景需要，把相关资产加载到内存或显存中，供引擎使用，并管理这些资源的生命周期

=== 具体设计

分为两个子模块:

. **asset/**: 资产管理相关功能,负责文件信息解析和转换
.. 根据文件格式不同，使用不同的parsers进行解析和转换，输出Asset类型的数据格式
.. asset拥有者为AM, AM管理Asset生命周期，外部只能使用不能自行创建和销毁
. **resource/**: 运行时资源管理功能，负责把转换后的引擎内部文件信息(Asset中的具体的单个资源)按需加载和销毁
.. 在场景加载时，根据场景需要的具体资产，在渲染过程中上传到显存中

==== 类设计

核心类与核心成员及其关系如下:

[plantuml]
....
class AssetManager {
    + Asset* createAsset(AssetCreateInfo info)
    + void destroyAsset(Asset* asset)
}
class Asset {
    - String mId
    - Container<Entity> mScenGraphEntities
    - Container<TextureHandle> mTextures
    - Container<MeshHandle> mMeshes
    - Container<MaterialHandle> mMaterials
}
Interface Parser {
    + {abstract} void parse(Asset& asset)
}
class GltfParser implements Parser {
    + void parse(Asset& asset)
}
class ResourceEntry {
    + Resource* pResource
    + uint32_t refCount
    + bool gcFlag
}
class ResourceManager{
    + ResourceHandle registerResource(Resource&& resource)
    + void unregisterResource(ResourceHandle handle)
    + void load(ResourceHandle handle)
    + void gc()
    + void clearAll()

    - Container<ResourceId, ResourceEntry> mRegistry

    - ResourceId generateId()
}
Interface Resource {
    + {abstract} void load()
    + {abstract} void unload()
    + Status status()

    - Status mStatus
}
class TextureResource implements Resource {
    + void load()
    + void unload()

    - RhiHandle<Texture> mRhiTexture
}
class Primitive {
    - RhiHandle<Buffer> mVertexBuffer
    - RhiHandle<Buffer> mIndexBuffer
    - MaterialHandle mMaterial
}
class MeshResource implements Resource {
    + void load()
    + void unload()
    
    - Container<Primitive> mPrimitives
}
class MaterialResource implements Resource {
    + void load()
    + void unload()

    - RhiHandle<DescriptorSet> mDescriptorSet
    - TextureHandle mBaseColor
    - TextureHandle mNormal
}
class Handle {
    - uint32_t mId
    - uint32_t mGeneration
}
class ResourceHandle<? extends Resource> extends Handle {
    - String name
}

AssetManager "1"*--"n" Asset
AssetManager "1"*--"n" Parser
Asset "1"o--"n" ResourceHandle
ResourceManager "1"*--"n" ResourceEntry
ResourceEntry "1"*--"1" Resource
ResourceManager "1"*--"n" ResourceHandle
Resource "1"<--"n" ResourceHandle
MeshResource "1"*--"n" Primitive
Primitive "1"o--"1" MaterialResource
MaterialResource "1"o--"n" TextureResource
....

==== 核心调用链

创建和销毁资产的核心调用链如下：

[plantuml]
....
actor developer as User order 1
participant AssetManager as Am order 2
participant Parser as Parser order 3
participant ResourceManager as Rm order 4
Rm -> Rm++: initialize()
Am -> Am++: initialize()
participant Parser [
  =Parser
  ----
  ""GltfParser""
]
Am -> Parser++: initialize()
group 创建资产 [gltf]
    User -> Am: createAsset()
    Am -> Am: 验证/读取文件
    activate Am #005500
    Am -> Parser: parse(Asset& asset)
    Parser -> Parser: 解析mesh, texture, material
    Parser -> Rm: registerResource(Resource& rsc)
    activate Rm #0099f2
    Parser <-- Rm: ResourceHandle
    Parser -> Parser: build scene
    Am <-- Parser: 填充后的Asset
    User <-- Am: Asset
end
group 销毁资产
    User -> Am: destroyAsset()
    Am -> Rm: unregisterResource()
    Rm -> Rm: 添加清除标记
    ...
    Rm -> Rm: gc()
    deactivate Rm
    deactivate Am
end
....

使用阶段涉及场景管理，见后文

=== 测试

. 测试文件信息正确读取并解析成对应数据钢结构，见test/test_asset.cpp
. 测试把Asset注册到resource manager,并在运行时正确加载到内存中
.. 注：GPU资源上传相关功能暂不测试，会在其他模块中一起测试

== 场景管理模块

=== 职责

. 运行时加载场景，管理场景内的物体生命周期
. 确定物体的类型，行为，属性，存储/读取物体数据
. 物体间的交互行为，关联关系
. 场景更新

=== 功能

. 场景图
. 场景描述功能
. 事件系统

=== 本版边界

. 实现静态object model, scene graph，场景加载
. 不做脚本系统
. 不做场景持久化，序列化
. 不做流式加载和世界块，只做单场景
. 不做运行时生成实体

=== 设计思路

. object model: 采用ECS(其实更像filament的Entity-Manager模式)实现属性中心式对象模型
.. 没有单独的system， 场景逻辑在Scene，由于需要多manager协调，由SceneBuilder代劳，Scene保持纯净，渲染逻辑在Renderer(见后文)
. 场景图采用Entity + Component描述并实现
. 提供给开发者SceneDescription接口, 可操作scene内对象和逻辑，不直接接触scene
. 场景只描述场景本身的内容，不代表渲染时有哪些实际要显示
. 分离出视图(view)代表从哪里看，怎么看，其范畴大于相机
. 事件系统区分，场景事件独立于引擎全局事件

=== 具体设计

场景管理模块放在**scene/**目录下

核心类，核心成员的类图如下:

[plantuml]
....
Interface SceneDescriptor{
    + {abstract} void onLoad(SceneBuilder& builder)
    + {abstract} void onUnLoad(Scene& builder)
}
class Scene{
    + void addEntity(Entity e)
    + void removeEntity(Entity e)
    + bool hasEntity(Entity e)

    - Container<Entity> mEntities
    - Container<View*> mViews
    - Skybox mSkyBox
}
class Entity{
    - uint32_t mId
    - uint32_t mGeneration
}
class EntityManager {
    + Entity create()
    + bool hasEntity()
    - uint32_t generateId()
}

class TransformManager{
    + Entity create()
    + Transform* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Transform> mTransforms
}
class RenderableManager {
    + Entity create()
    + Renderable* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Renderable> mRenderables
}
class LightManager {
    + Entity create()
    + Light* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Light> mLights
}
class Light <<Component>> {
    - LightType mType
    - vec3 mColor
    - float mIntensity
}

class Transform <<Component>> {
    - vec3 mPosition
    - vec4 mRotation
    - vec3 mScale
    - Entity mParent
    - Container<Entity> mChildren
    - bool dirtyFlag
}
class Renderable <<Component>> {
    - ResourceHandle<MeshResource> mMeshHandle
    - ResourceHandle<MaterialResource> mMaterialHandle
}
class CameraManager {
    + Entity create()
    + Camera* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Camera> mCameras
}

class Camera <<Component>> {
    - ProjectionType mProjType
    - float zNear
    - float zFar
    - float mHFov
    - float mAspectRatio
}

class View {
    - Viewport mViewport
    - Entity mMainCamera
    - Scene* mScene
}

class Viewport {
    - float x
    - float y
    - float width
    - float height
}


Scene "1"o--"n" Entity
Scene "1" o--"n" View
TransformManager "1"*--"n" Transform
RenderableManager "1"*--"n" Renderable
CameraManager "1"*--"n" Camera
LightManager "1"*--"n" Light
EntityManager "1"*--"n" Entity
View "1"*--"1" Viewport
View "1"o--"1" Camera
Scene <.. SceneDescription
....

=== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescription as SD order 30
participant SceneBuilder as SB order 40
participant EntityManager as EM order 50
participant TransformManager as TM order 60
participant RenderableManager as RM order 70
participant CameraManager as CM order 90
participant LightManager as LM order 100
participant Scene as Scene order 110
participant View as View order 120
User -> Engine++: 创建并初始化
User -> SD: 派生并实现
User -> Engine: loadScene
Engine -> Scene++: new Scene()
Engine -> SB++: new SceneBuilder(Scene&)
Engine -> SD++: onLoad(builder)
group 生成场景图
    SB -> Scene: createView()
    Scene -> View++: new
    Scene <-- View: View
    SB -> EM: create()
    SB <-- EM: entity
    SB -> TM: create(entity)
    TM -> TM: new Transform
    SB <-- TM
    ... 在其他Manager中创建entity,同上 ...
    SB -> Scene: addEntity(entity)
    SB -> SB: 配置view, scene, camera等关系
end
Engine <-- SB--: Scene
group 卸载场景
    Engine -> Engine: render loop退出
    Engine -> SD: onUnload(SceneBuilder&)
    SD -> SD: 自定义逻辑
    SD -> Scene: clear()
    Scene -> View: destroy view
    deactivate View
    Scene -> RM: destroy()
    ... 其他manager同上 ...
    Engine <-- Scene--
    Engine -> Engine: 执行内部清理逻辑
end
....

此处渲染时场景读取的调用链暂略，详见渲染模块设计

== 渲染模块

=== 职责

. 根据场景描述收集渲染数据, 裁剪出需要渲染的部分
. 请求资源系统确保所需资源可用
. 描述渲染的流程(render pass及其组合)，渲染的方式(forward/deferred shading), 渲染的技术(PBR)
. 构建并管理每帧数据
. 根据pass生成render graph, 自动优化和确保同步机制，给出pass和资源的依赖关系，推导资源生命周期，按顺序执行
. 生成并录制渲染命令，提交到渲染底层(RHI)
. 界面绘制，后处理特效，及其他相关功能
. 渲染相关的多线程任务调度

=== 功能

. render pass
. render graph
. custom & flexible shading path(deferred/forward)
. pbr， ibl, directional shadow, tonemap

=== 边界

. 本版暂不集成job system
. 暂不做多线程命令录制
. 不直接操作和接触RM和RHI层的资源，只描述操作过程
. 以实现功能为主，设计上采用数据驱动和自动rg，架构上会预留扩展空间，但暂不保证测试覆盖，和性能

=== 设计思路

. 以render pass描述pass，可以通过render graph组织依赖关系，优化执行顺序，优化资源读写
. render graph支持自动屏障插入，不需要手动管理pass之间的依赖和操作同步原语
. renderer不会去直接与底层资源和内存资源交互，而是通过handle
. renderer带有自己的内存管理器，主要用于管理帧内资源，实现高效分配和回收，保证内存局部性和连续性

=== 具体设计

渲染模块放在**rendering/**目录下

==== 核心类及成员

[plantuml]
....
class Renderer {
    + void renderFrame(View& view)
    - void beginFrame()
    - void endFrame()

    - ResourceManager& mResourceManager
    - FrameContext mFrameContext
    - Container<FrameData> mPerFrameData
    - RenderGraph mRenderGraph
    - Driver& mDriver
}
class Driver {
  + {abstract} void acquireNextFrame()
  + {abstract} void startCmdRecording()
  + {abstract} void endCmdRecording()
  + {abstract} void submitFrame()
  + {abstract} void presentFrame()
  + {abstract} void endFrame()
  + {abstract} HwTexture& createTexture(TextureResource& resource)
  + {abstract} HwBuffer& createBuffer(BufferResource& resource)
}
class RenderPass {
    + void inputResource(ResourceHandle handle)
    + void outputResource(ResourceHandle handle)
    + void execute()

    - Container<ResourceHandle> mInputs
    - Container<ResourceHandle> mOutputs

}
class RenderGraph{
    + void addPass(RenderPass&& pass)
    + void compile()
    + void execute()

    - Driver& mDriver
    - Container<ResourceNode::IdType> mExecutionOrder
}

Renderer o-- Driver
Renderer *-- RenderGraph
RenderGraph "1"*--"n" RenderPass
....

==== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescriptor as SD order 30
participant Renderer as Renderer order 40
participant RenderGraph as RG order 42
participant Driver as Driver order 50
participant Scene as Scene order 60
participant View as View order 70

User -> Engine++: initialize()
Engine -> Driver++: new
Engine -> Renderer++: new
Renderer -> RG++: new
Engine -> Scene++: new
Engine -> View++: new
User -> Engine: loadScene()
Engine -> SD++: new
User -> Engine: run()
Engine -> SD: onLoad()
SD -> Scene: 重置并准备场景数据
SD -> View: 重置并准备视图，相机配置
group mainLoop
    Engine -> Renderer: beginFrame()
    Renderer -> Driver:  acquireNextFrame()
    Renderer <-- Driver: finish frame data update and syncing
    Engine <-- Renderer
    Engine -> View: update()
    Engine -> Scene: update()
    Engine -> Renderer: renderFrame()
    Renderer -> Renderer: View, Scene数据剔除，抽取, 写到PerFrameData
    Renderer -> RG: reset()
    Renderer -> RG: addPass()
    Renderer -> RG: compile()
    Renderer -> RG: execute()
    Engine <-- Renderer
Engine -> Renderer: endFrame()
Renderer -> Driver: submitFrame()
Renderer -> Driver: presentFrame()
Renderer -> Driver: endFrame()
end
....

== 图形后端(底层渲染)模块

=== 职责

. 向渲染层提供统一的API，使其能操作backend资源
. 将接口调用映射到具体图形API实现
. 可描述，管理，操作backend的GPU资源
. 可完整支持并隔离上层渲染操作

=== 功能

. rhi接口，rhi资源描述和管理
. rhi实现，底层API的封装
. 底层API的资源管理
. slangc加载，shader资源管理

=== 边界

. 不实现多backend，只实现vulkan backend
. 暂不实现完整RHI，只预留接口

=== 具体设计

==== 核心类及成员

==== 核心调用链

