= 模块设计简述

== Engine模块

=== 职责

. 主入口
. 暴露必要API给外部操作
. 拥有全部子系统
. 子系统的生命周期管理
. 其他需要全局协调的相关事务

==== 设计思路

. 不执行具体逻辑
. 显式，命令式进行子系统的创销逻辑
. 子系统之间的非核心调用通过事件系统解耦
. 在主线程上，负责main loop的顶层统筹
. 平台层在engine内部处理，不在外部

== core模块

提供引擎全局基础能力，目前应包括：

. 引擎无关的通用工具
.. 日志
.. 调试
.. 自定义容器
.. 序列化
.. 数学
.. 性能剖析
.. 内存分配器
.. job system
. 全局配置项
. 全局基类和接口定义

=== 思路

. 尽量纯头文件
. 使依赖尽量少
. 工具类尽量独立于引擎
. 如果涉及三方库类型，尽量在此处封装，不把三方库类型传播到引擎内部，如果传播，尽量使其范围可控

=== 内存管理

==== 设计思路

自研高性能内存管理器Arena：

* Policy-Based Class Template实现，内存资源和分配算法分离
* 支持内存追踪，线程安全, 内存对齐
* 自带对象池实现，使用TLSF实现
* 预留了跨平台扩展性
* 预留了其他内存资源, 分配算法的扩展性

== 资产/资源管理模块

. 资源的加载整体上分为两块，资产管理和资源管理,此处分别称为(Asset Management(AM)和Resource Management(RM))
.. AM: 负责硬盘文件信息读取，并解析转换为运行时资源信息，本身不负责直接加载数据，只解析和转换相关文件的信息，并提供把转换好的资产"注册"到运行时资源管理中
.. RM: 利用资产管理解析的文件信息，在运行时按照场景需要，把相关资产加载到内存或显存中，供引擎使用，并管理这些资源的生命周期
. AM,RM解耦，各自管理相关的数据
. 不与其他子系统耦合，比如场景系统
. AM: 
.. 输入: 是资产文件预制件(prefab)，预留各种类型预制件的处理空间，此版支持gltf格式,输出为引擎标准化的数据(asset)
.. 输出: asset数据，外部使用指针访问, AM管理Asset的生命周期
. RM:
.. 输入: Asset, 转为各种resource，并负责resource的生命周期，加载，卸载过程
.. 输出: resource的handle

=== 设计思路

. RM: 类型安全，以handle作为凭据，支持多线程异步，异步任务分派给job system执行，防重
.. RM管理的叫做resource，分为mesh resource, texture resource, buffer resource等，是由Asset拆分出来的，但RM不依赖Asset
.. RM持有资源的实际数据,不是AM
. AM: 无论哪种格式，统一转换为Asset，通过向RM注册Asset生成资源, Asset可以重复注册到RM，但Asset和Asset生成的Resources都只有一份,不同的handle可对应同一个resource
.. AM会在加载完成后把资产注册到RM中，同时移交相关数据，Asset本身只有资源描述信息，不持有转换后的数据

=== 功能

.AM
. 文件读取：支持读取gltf模型, ktx, png等格式的纹理
.. 支持单一和复合型资产，比如gltf
. 文件转换: 可把上述格式的文件转换为对应引擎内部Asset数据结构
.. 建立资源之间的引用关系
.. 生成gltf场景节点,但与场景管理解耦

.RM
. 资源注册: 保证资源唯一,记录文件基本信息，生成资源id,创建资源对象
. 资源加载/卸载: 控制资源加载/卸载时机，管理资源状态
. 资源句柄: 资源可外部引用，但由RM内部管理生命周期
. 异步加载，卸载资源

=== 本版边界

. 实现gltf和ktx的读取，解析，转换，运行时加载，正确渲染
. 不实现gltf的蒙皮，动作，多场景解析
. 不实现流式加载，热重载
. 不实现gltf修改，导出
. 预留不实现功能的扩展性

=== 具体设计

分为两个子模块:

. **asset/**: 资产管理相关功能,负责文件信息解析和转换
.. 根据文件格式不同，使用不同的parsers进行解析和转换，输出Asset类型的数据格式
.. asset拥有者为AM, AM管理Asset生命周期，外部只能使用不能自行创建和销毁
. **resource/**: 运行时资源管理功能，负责把转换后的引擎内部文件信息(Asset中的具体的单个资源)按需加载和销毁
.. 在场景加载时，根据场景需要的具体资产，真正加载到GPU侧中

==== 类设计

核心类与核心成员及其关系如下,依旧只体现思路，很可能与实际代码不一样，若需查看详细准确的实现，请参考源代码:

[plantuml]
....
class AssetManager {
    资产管理：负责读取文件，转换为内部数据格式，输出Asset，管理Asset生命周期
    ==
    + Asset* createAsset(AssetCreateInfo info)
    + void destroyAsset(Asset& asset)
    ==
    - unordered_map<AssetId, Asset*> mAssets
    - unordered_map<ParserIndex, Parser*> mParsers

    - void parseAsset(Asset& asset)
}
class Asset {
    资源对象: 资产转换后引擎内部统一的数据结构
    ==
    - u64 mId
    - String mName
    - vector<Node> mNodes
    - vector<TextureInfo> mTextures
    - vector<MeshData*> mMeshes
}
Interface Parser {
    把资产文件转换并填充到asset中,在AM中注册资源拿到句柄
    ==
    + {abstract} void parse(Asset& asset)
}
class GltfParser implements Parser {
    gltf解析器
    ==
    + void parse(Asset& asset) override
}
class ResourceManager{
    管理运行时资源，利用对象池,内存池
    ==
    + void loadAsset(Asset* asset)
    + ResourceHandle registerResource(Resource&& resource)
    + void unregisterResource(ResourceHandle handle)
    + void load(ResourceHandle handle)
    + void unload(ResourceHandle handle)
    + void gc()
    + void clearAll()
    --
    - Map<ResourceId, ResourceEntry> mRegistry
    - ObjectPool<Resource> mData
    --
}
Interface Resource {
    资源接口:定义资源操作
    ==
    + {abstract} void load()
    + {abstract} void unload()
    + Status status()
    --
    - uint64_t mId
    - Status mStatus
}
class TextureResource implements Resource {
    纹理资源数据
    ==
    + void load() override
    + void unload() override
    --
    - Handle<HwTexture> mHwTexture
}
class MeshResource implements Resource {
    网格资源
    ==
    + void load() override
    + void unload() override
    --
    - vector<MeshData*> mRawData
    - Handle<HwBuffer> mVertexBuffer
    - Handle<HwBuffer> mIndexBuffer
}
class MaterialResource implements Resource {
    材质资源
    ==
    + void load()  override
    + void unload()  override
    --
    - BackendHandle<DescriptorSet> mDescriptorSet
    - TextureHandle mBaseColor
    - TextureHandle mNormal
}
class Handle {
    分代句柄基类
    ==
    - uint32_t mId
    - uint32_t mGen
}

class ResourceHandle<? extends Resource> extends Handle {
    类型安全的资源句柄
    ==
}

AssetManager "1"*--"n" Asset
AssetManager "1"*--"n" Parser
ResourceManager "1"*--"n" ResourceHandle
ResourceManager "1"*--"n" Resource
....

==== 核心调用链

创建和销毁资产的核心调用链如下：

[plantuml]
....
actor developer as User order 1
participant AssetManager as Am order 2
participant Parser as Parser order 3
participant ResourceManager as Rm order 4
Rm -> Rm++: initialize()
Am -> Am++: initialize()
participant Parser [
  =Parser
  ----
  ""GltfParser""
]
Am -> Parser++: initialize()
group 创建资产 [gltf]
    User -> Am: createAsset()
    Am -> Am: 验证/读取文件
    activate Am #005500
    Am -> Parser: parse(Asset& asset)
    Parser -> Parser: 解析mesh, texture, material
    Am <-- Parser: parsed asset
    User <-- Am: Asset*
end
group 销毁资产
    User -> Am: destroyAsset()
    Am -> Rm: unloadAsset()
    Rm -> Rm: 添加清除标记
    ...
    Rm -> Rm: gc()
    deactivate Rm
    deactivate Am
end
....

使用阶段涉及场景管理，见后文

=== 测试

. 测试文件信息正确读取并解析成对应数据钢结构，见test/test_asset.cpp
. 测试把Asset注册到resource manager,并在运行时正确加载到内存中
.. 注：GPU资源上传相关功能暂不测试，会在Backend模块中一起测试

== 场景管理模块

=== 职责

. 运行时加载场景，管理场景内的物体生命周期
. 确定物体的类型，行为，属性，存储/读取物体数据
. 物体间的交互行为，关联关系
. 场景更新

=== 功能

. 场景图
. 场景描述
. 视图，相机

=== 本版边界

. 实现静态object model, scene graph，场景加载
. 不做脚本系统
. 不做场景持久化，序列化
. 不做流式加载和世界块，只做单场景
. 不做运行时生成实体

=== 设计思路

. 采用数据驱动设计(ECS)，实现属性中心式的对象模型
. 职责纯净，不耦合于其他模块，只描述场景本身的内容和相关数据，不负责可见性剔除等操作
. 使用者通过SceneDescriptor接口实现可插拔的资源加载和场景描述
. 分离出视图(view)代表从哪里看，怎么看，一个场景可有多个视图，代表屏幕内的子视窗，可对应多个相机

=== 具体设计

场景管理模块放在**scene/**目录下

核心类，核心成员的类图如下:

[plantuml]
....
Interface ISceneDescriptor{
    + {abstract} void onSceneLoad(SceneManager& mgr)
    + {abstract} void onSceneUpdate(float deltaTime, SceneManager& mgr)
    + {abstract} void onSceneUnLoad(SceneManager& mgr)
}
class SceneManager {
    场景管理器: 负责统一管理场景内数据和视图
    ==
    + void resetScene()
    + void loadScene(ISceneDescriptor* sceneDescriptor)
    + Scene* getScene()
    + View* createView(string name)
    + View* getView(string name)
    + void removeView(string name)
    --
    - Scene mScene
    - vector<Renderable> mRenderables
    - ISceneDescriptor* mSceneDescriptor
    - vector<View*> mViews
    - EntityManager mEntityManager
}
class Scene {
    + void addEntity(Entity e)
    + void removeEntity(Entity e)
    + bool hasEntity(Entity e)
    --
    - Container<Entity> mEntities
    - Container<View*> mViews
    - Skybox mSkyBox
}
class Entity{
    - uint32_t mId
    - uint32_t mGen
}

class EntityManager {
    实体管理器：负责分发entity
    ==
    + Entity create()
    + bool hasEntity()
    - uint32_t generateId()
}

class View {
    场景中的视图: 定义在场景的哪里看，怎么看
    ==
    --
    - String mName
    - Viewport mViewport
    - Entity mMainCamera
    - Scene* mScene
}

class Camera {
    ==
    - Type type
    - float zNear
    - float zFar
    - float hFov
    - float aspectRatio
}

class Viewport {
    视口：定义视图里看哪里，多大范围
    ==
    --
    - float x
    - float y
    - float width
    - float height
}

SceneManager *-- Scene
SceneManager *-- View
SceneManager *-- EntityManager
SceneManager *-- Renderable
SceneManager *.. ISceneDescriptor
Scene "1"o--"n" Entity
Scene "1" o--"n" View
EntityManager "1"*--"n" Entity
Renderable <.. Entity
Camera <.. Entity
View "1"*--"1" Viewport
View "1"o--"1" Camera
....

=== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescriptor as SD order 30
participant SceneManager as SM order 40
participant EntityManager as EM order 50
participant Scene as Scene order 110
participant View as View order 120
User -> Engine++: 创建并初始化
Engine -> SM: new
SM -> Scene++: new
SM -> EM++: new
User -> SD: 派生并实现
User -> Engine: loadScene()
Engine -> SM: loadScene()
SM -> SM: resetScene()
SM -> SD: onLoad()
group 加载场景
    SD -> SM: createView()
    SM -> View++: new
    SM <- View: view
    SD -> EM: create()
    SD <-- EM: entity
    SD -> EM: addComponent<Transform>(entity)
    ... 创建entity对应的component数据, 方法同上 ...
    SD -> Scene: addEntity(entity)
    SD -> SD: 配置view, scene, camera等关系
end
SM -> Engine: 完成场景加载
... main loop ...
Engine -> Engine: main loop退出
group 卸载场景
    Engine -> SM: unloadScene()
    SM -> SD: onUnload()
    SD -> SD: 自定义场景卸载逻辑
    SM -> SM: clearScene()
    Engine <- SM: 场景数据清理完毕
    Engine -> Engine: ResourceManager::clearAll()
end
....

此处渲染时场景读取的调用链暂略，详见渲染模块设计

== 渲染模块

[NOTE]
====
此模块设计改动较大，文档很可能不准确, 正在更新中
====

=== 职责

. 根据场景描述收集渲染数据, 裁剪出需要渲染的部分
. 请求资源系统确保所需资源可用
. 描述渲染的流程(render pass及其组合)，渲染的方式(forward/deferred shading), 渲染的技术(PBR)
. 构建并管理每帧数据
. 根据pass生成render graph, 自动优化和确保同步机制，给出pass和资源的依赖关系，推导资源生命周期，按顺序执行
. 生成并录制渲染命令，提交到渲染底层(RHI)
. 界面绘制，后处理特效，材质系统，gui layer及其他相关功能
. 渲染相关的多线程任务调度

=== 功能

. render pass
. render graph
. custom & flexible shading path(deferred/forward)
. pbr， ibl, directional shadow, tonemap

=== 边界

. 暂不做多线程命令录制
. 不直接操作和接触RM和RHI层的资源，只描述操作过程
. 以实现功能为主，设计上采用数据驱动和自动rg，架构上会预留扩展空间，但暂不保证测试覆盖，和性能

=== 设计思路

. 以render pass描述pass，可以通过render graph组织依赖关系，优化执行顺序，优化资源读写
. render graph支持自动屏障插入，不需要手动管理pass之间的依赖和操作同步原语
. renderer不会去直接与底层资源和内存资源交互，而是通过handle
. renderer带有自己的内存管理器，主要用于管理帧内资源，实现高效分配和回收，保证内存局部性和连续性

=== 具体设计

渲染模块放在**rendering/**目录下

==== 核心类及成员

[plantuml]
....
class Renderer {
    + void renderFrame(View& view)
    - void beginFrame()
    - void endFrame()

    - IBackend* mBackend
    - ResourceManager& mResourceManager
    - FrameContext mFrameContext
    - Container<FrameData> mPerFrameData
    - RenderGraph mRenderGraph
}
class Driver {
  + {abstract} void acquireNextFrame()
  + {abstract} void startCmdRecording()
  + {abstract} void endCmdRecording()
  + {abstract} void submitFrame()
  + {abstract} void presentFrame()
  + {abstract} void endFrame()
  + {abstract} HwTexture& createTexture(TextureResource& resource)
  + {abstract} HwBuffer& createBuffer(BufferResource& resource)
}
class RenderPass {
    + void inputResource(ResourceHandle handle)
    + void outputResource(ResourceHandle handle)
    + void execute()

    - Container<ResourceHandle> mInputs
    - Container<ResourceHandle> mOutputs

}
class RenderGraph{
    + void addPass(RenderPass&& pass)
    + void compile()
    + void execute()

    - Driver& mDriver
    - Container<ResourceNode::IdType> mExecutionOrder
}

Renderer o-- Driver
Renderer *-- RenderGraph
RenderGraph "1"*--"n" RenderPass
....

==== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescriptor as SD order 30
participant Renderer as Renderer order 40
participant RenderGraph as RG order 42
participant Driver as Driver order 50
participant Scene as Scene order 60
participant View as View order 70

User -> Engine++: initialize()
Engine -> Driver++: new
Engine -> Renderer++: new
Renderer -> RG++: new
Engine -> Scene++: new
Engine -> View++: new
User -> Engine: loadScene()
Engine -> SD++: new
User -> Engine: run()
Engine -> SD: onLoad()
SD -> Scene: 重置并准备场景数据
SD -> View: 重置并准备视图，相机配置
group mainLoop
    Engine -> Renderer: beginFrame()
    Renderer -> Driver:  acquireNextFrame()
    Renderer <-- Driver: finish frame data update and syncing
    Engine <-- Renderer
    Engine -> View: update()
    Engine -> Scene: update()
    Engine -> Renderer: renderFrame()
    Renderer -> Renderer: View, Scene数据剔除，抽取, 写到PerFrameData
    Renderer -> RG: reset()
    Renderer -> RG: addPass()
    Renderer -> RG: compile()
    Renderer -> RG: execute()
    Engine <-- Renderer
Engine -> Renderer: endFrame()
Renderer -> Driver: submitFrame()
Renderer -> Driver: presentFrame()
Renderer -> Driver: endFrame()
end
....

== RHI模块

=== 职责

. 向渲染层提供统一的API，使其能操作backend资源
. 将接口调用映射到具体图形API实现
. 可描述，管理，操作backend的GPU资源
. 可完整支持并隔离上层渲染操作

=== 功能

. rhi接口
. rhi各种资源抽象
. rhi句柄
. rhi配置枚举

=== 边界

. 不实现多backend，只实现vulkan backend
. 暂不实现完整RHI， 只支持引擎需要的功能
. 第一版只基于vulkan，之后版本若实现其他backend在考虑做出进一步调整，也就是说实质上本版RHI是介于renderer和vulkan backend之间的一个适配器和便利设施
. 性能不是当前版本的首要考虑元素

=== 设计思路

. 注：其实当前引擎来说，RHI属于超前设计，不必须，但是我不想比如vulkan的句柄(即便已封装为handle)暴露到renderer或rendergraph中，导致以后写d3dx之类的backend得大幅度修改和兼容代码，另外自己也想做一层体会学习一下，故还是加了
. RHI对于当前的引擎来说，若存在，则应该解决的首要问题是底层图形api的操作便利性的问题，并为未来兼容其他backend预留余地，也就是说，RHI是基于backend能力，为renderer提供便利且高效服务的角色，一定程度上，会为renderer提供定制化的执行优化方案，不是可以独立于引擎的通用rhi，目前阶段也不会考虑RHI通用化，独立化
. RHI与backend抽象层解决的问题不同，前者解决具体渲染功能相关的操作便利性和兼容性问题，还承担了这些具体操作的优化责任，而后者解决的是底层资源的封装和管理，还有渲染无关的通用，基础操作封装
. 与rendergraph不同，前者只负责渲染功能的排布和更具体的资源和同步操作，rhi记录这些资源和同步的操作，优化并转换为backend操作，并递交给backend实际执行
. RHI只封装沉淀下来的通用操作，不封装和跨api兼容特定backend新特性，预留一个类似unsafe(或叫unstable)的入口搞特定未沉淀为通用操作的底层特性的接口，暴露出句柄，由上层使用者自行控制并承担风险
. 随着RHI框架演进，会把feature划入safe区或unsafe区
. RHI不是一簇而就的，不是全包统揽的，便利性就应该是RHI的追求，而且应该只考虑包括已沉淀下来的通用操作，而不是支持新特性，过于暴露底层就相当于画蛇添足额外加了一层abstraction layer
. 不认为要严封装，只认为要务实，会给使用者底层句柄权限，方便实现特定功能，只是受限，且后果自负
. 主要使用者是renderer和render graph,目前阶段以支持所需的操作为主,强调易用性，底层细节和优化自由度隐藏在rhi之后，不暴露过多细节，关键概念都尽量简化，能不暴露就不暴露，为未来的rhi底层优化留足余地。RHI的优化应该由RHI内部负责，而不是外部使用者，过多的暴露抽象和操作给外部，只会降低底层优化空间，加大迭代和维护难度
. rhi底部的backend封装层尽量薄，只包含基本操作和句柄，不负责具体的执行逻辑，只提供方便操作的基础的接口，要玩花样和高级功能的责任由RHI层负责
. RHI的位置是在renderer和backend之间提供适配和易用的功能，且承担了面向renderer特化的性能实现，对底层backend和上层renderer都隐藏实现细节。

==== 核心类及成员

==== 核心调用链

== vulkan后端

=== 职责

. 具体执行渲染绘制指令
. 对底层资源进行生命周期管理
. 对底层操作进行便利封装
. 继承RHI接口并提供实际功能实现

=== 功能

. 支持执行各种绘制指令
. 基础vulkan功能运行正常，功能点可扩展
. 资源和同步管理

=== 边界

. 主要保证渲染层需要的基础能力，暂不做高度优化

=== 具体设计

