= 模块设计简述

== Engine模块

=== 职责

. 主入口
. 暴露必要API给外部操作
. 拥有全部子系统
. 子系统的生命周期管理
. 其他需要全局协调的相关事务

==== 设计思路

. 不执行具体逻辑
. 显式，命令式进行子系统的创销逻辑
. 子系统之间的非核心调用通过事件系统解耦

== core模块

提供引擎全局基础能力，包括：

. 日志
. 调试
. 性能剖析
. 全局配置项
. 全局基类和接口定义
. 全局便利工具
.. 内存管理
.. job system

=== 内存管理

==== 设计思路

自研高性能内存管理器Arena：

* Policy-Based Class Template实现，内存资源和分配算法分离
* 支持内存追踪，线程安全, 内存对齐
* 自带对象池实现，使用TLSF实现
* 预留了跨平台扩展性
* 预留了其他内存资源, 分配算法的扩展性

=== 事件系统

==== 设计思路

== 资产/资源管理模块

作为整个引擎的大动脉，是必须清晰整理数据流，逻辑流，状态流

=== 设计思路

. 资源的加载整体上分为两块，资产管理和资源管理,此处分别称为(Asset Management(AM)和Resource Management(RM))
.. AM: 负责硬盘文件信息读取，并解析转换为运行时资源信息，本身不负责直接加载数据，只解析和转换相关文件的信息，并提供把转换好的资产"注册"到运行时资源管理中
.. RM: 利用资产管理解析的文件信息，在运行时按照场景需要，把相关资产加载到内存或显存中，供引擎使用，并管理这些资源的生命周期
. AM,RM解耦，各自管理相关的数据
. 不与其他子系统耦合，比如场景系统

=== 功能

.AM
. 文件读取：支持读取gltf模型, ktx, png等格式的纹理 
.. 包括复合型资产拆分成子资产，比如gltf
. 文件转换: 可把上述格式的文件转换为对应引擎内部数据结构
.. 建立资源之间的引用关系
.. gltf场景图

.RM
. 资源注册: 保证资源唯一,记录文件基本信息
. 资源加载: 控制加载时机
. 资源句柄: 资源可外部引用，但由RM内部管理生命周期

=== 本版边界

. 实现gltf和ktx的读取，解析，转换，运行时加载，正确渲染
. 不实现gltf的蒙皮，动作，多场景解析
. 不实现异步多线程加载
. 不实现流式加载，热重载
. 不实现gltf修改，导出
. 预留不实现功能的扩展性

=== 具体设计

分为两个子模块:

. **asset/**: 资产管理相关功能,负责文件信息解析和转换
.. 根据文件格式不同，使用不同的parsers进行解析和转换，输出Asset类型的数据格式
.. asset拥有者为AM, AM管理Asset生命周期，外部只能使用不能自行创建和销毁
. **resource/**: 运行时资源管理功能，负责把转换后的引擎内部文件信息(Asset中的具体的单个资源)按需加载和销毁
.. 在场景加载时，根据场景需要的具体资产，在渲染过程中上传到显存中

==== 类设计

核心类与核心成员及其关系如下:

[plantuml]
....
class AssetManager {
    资产管理：负责读取文件，转换为内部数据格式，输出Asset，管理Asset生命周期
    ==
    + Asset* createAsset(AssetCreateInfo info)
    + void destroyAsset(Asset* asset)
    ==
    - Container<Asset*> mAssets
    - Container<Parser*> mParsers
}
class Asset {
    资源对象: 资产转换后数据，只持有句柄
    暂不对资产类型做进一步区分
    ==
    - String mId
    - Container<Node*> mSceneNodes
    - Container<TextureHandle> mTextures
    - Container<MeshHandle> mMeshes
    - Container<MaterialHandle> mMaterials
}
Interface Parser {
    把资产文件转换并填充到asset中,在AM中注册资源拿到句柄
    ==
    + {abstract} void parse(Asset& asset)
}
class GltfParser implements Parser {
    gltf解析器
    ==
    + void parse(Asset& asset)
}
class ResourceEntry {
    带引用计数和gc支持的资源指针
    ==
    + Resource* pResource
    + uint32_t refCount
    + bool gcFlag
}
class ResourceManager{
    管理运行时资源
    ==
    + ResourceHandle registerResource(Resource&& resource)
    + void unregisterResource(ResourceHandle handle)
    + void load(ResourceHandle handle)
    + void unload(ResourceHandle handle)
    + void gc()
    + void clearAll()
    --
    - Container<ResourceId, ResourceEntry> mRegistry
    --
    - ResourceId generateId()
}
Interface Resource {
    资源接口:定义资源操作
    ==
    + {abstract} void load()
    + {abstract} void unload()
    + Status status()
    --
    - Status mStatus
}
class TextureResource implements Resource {
    纹理资源数据
    ==
    + void load()
    + void unload()
    --
    - BackendHandle<HwTexture> mHwTexture
}
class Primitive {
    网格的submesh或primitive
    ==
    --
    - BackendHandle<HwBuffer> mVertexBuffer
    - BackendHandle<HwBuffer> mIndexBuffer
    - MaterialHandle mMaterial
}
class MeshResource implements Resource {
    网格资源
    ==
    + void load()
    + void unload()
    --
    - Container<Primitive> mPrimitives
}
class MaterialResource implements Resource {
    材质资源
    ==
    + void load()
    + void unload()
    --
    - BackendHandle<DescriptorSet> mDescriptorSet
    - TextureHandle mBaseColor
    - TextureHandle mNormal
}
class Handle {
    句柄基类，可支持分代
    ==
    - uint32_t mId
    - uint32_t mGen
}

class ResourceHandle<? extends Resource> extends Handle {
    类型安全的资源句柄
    ==
}

AssetManager "1"*--"n" Asset
AssetManager "1"*--"n" Parser
Asset "1"o--"n" ResourceHandle
ResourceManager "1"*--"n" ResourceEntry
ResourceEntry "1"*--"1" Resource
ResourceManager "1"*--"n" ResourceHandle
Resource "1"<--"n" ResourceHandle
MeshResource "1"*--"n" Primitive
Primitive "1"o--"1" MaterialResource
MaterialResource "1"o--"n" TextureResource
....

==== 核心调用链

创建和销毁资产的核心调用链如下：

[plantuml]
....
actor developer as User order 1
participant AssetManager as Am order 2
participant Parser as Parser order 3
participant ResourceManager as Rm order 4
Rm -> Rm++: initialize()
Am -> Am++: initialize()
participant Parser [
  =Parser
  ----
  ""GltfParser""
]
Am -> Parser++: initialize()
group 创建资产 [gltf]
    User -> Am: createAsset()
    Am -> Am: 验证/读取文件
    activate Am #005500
    Am -> Parser: parse(Asset& asset)
    Parser -> Parser: 解析mesh, texture, material
    Parser -> Rm: registerResource(Resource& rsc)
    activate Rm #0099f2
    Parser <-- Rm: ResourceHandle
    Parser -> Parser: build scene
    Am <-- Parser: 填充后的Asset
    User <-- Am: Asset
end
group 销毁资产
    User -> Am: destroyAsset()
    Am -> Rm: unregisterResource()
    Rm -> Rm: 添加清除标记
    ...
    Rm -> Rm: gc()
    deactivate Rm
    deactivate Am
end
....

使用阶段涉及场景管理，见后文

=== 测试

. 测试文件信息正确读取并解析成对应数据钢结构，见test/test_asset.cpp
. 测试把Asset注册到resource manager,并在运行时正确加载到内存中
.. 注：GPU资源上传相关功能暂不测试，会在Backend模块中一起测试

== 场景管理模块

=== 职责

. 运行时加载场景，管理场景内的物体生命周期
. 确定物体的类型，行为，属性，存储/读取物体数据
. 物体间的交互行为，关联关系
. 场景更新

=== 功能

. 场景图
. 场景描述
. 其他功能

=== 本版边界

. 实现静态object model, scene graph，场景加载
. 不做脚本系统
. 不做场景持久化，序列化
. 不做流式加载和世界块，只做单场景
. 不做运行时生成实体

=== 设计思路

. 采用数据驱动架构，实现属性中心式的对象模型
. 职责纯净，不耦合于其他模块，只描述场景本身的内容和相关数据，不负责可见性剔除等操作
. 使用者通过SceneDescriptor接口实现可插拔的资源加载和场景描述
. 分离出视图(view)代表从哪里看，怎么看，一个场景可有多个视图，代表屏幕内的子视窗，可对应多个相机

=== 具体设计

场景管理模块放在**scene/**目录下

核心类，核心成员的类图如下:

[plantuml]
....
Interface ISceneDescriptor{
    + {abstract} void onLoad(AssetManager& assetMgr, SceneManager& sceneMgr)
    + {abstract} void onUnLoad(AssetManager& assetMgr, SceneManager& mgr)
}
class SceneManager {
    场景管理器: 负责统一管理场景内数据和视图
    ==
    + void resetScene()
    + void loadScene(ISceneDescriptor* sceneDescriptor)
    + Scene* getScene()
    + View* createView(string name)
    + View* getView(string name)
    + void removeView(string name)
    --
    - Scene mScene
    - ISceneDescriptor* mSceneDescriptor
    - Container<string, View*> mViews
    - EntityManager mEntityManager
    - TransformManager mTransformManager
    - RenderableManager mRenderableManager
    - LightManager mLightManager
    - CameraManager mCameraManager
}
class Scene {
    + void addEntity(Entity e)
    + void removeEntity(Entity e)
    + bool hasEntity(Entity e)
    --
    - Container<Entity> mEntities
    - Container<View*> mViews
    - Skybox mSkyBox
}
class Entity{
    - uint32_t mId
    - uint32_t mGen
}

class EntityManager {
    实体管理器：负责分发entity
    ==
    + Entity create()
    + bool hasEntity()
    - uint32_t generateId()
}

class BaseComponentsManager {
    entity的各component组件管理器基类
    ==
    + Entity create()
    + Transform* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)
}

class TransformManager extends BaseComponentsManager {
    entity的变换数据管理
    ==
    + Entity create()
    + Transform* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Transform> mTransforms
}
class RenderableManager  extends BaseComponentsManager {
    entity的渲染数据管理
    ==
    + Entity create()
    + Renderable* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Renderable> mRenderables
}
class LightManager  extends BaseComponentsManager {
    entity的光源数据管理
    ==
    + Entity create()
    + Light* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Light> mLights
}
class Light <<Component>> {
    - LightType mType
    - vec3 mColor
    - float mIntensity
}

class Transform <<Component>> {
    - vec3 mPosition
    - vec4 mRotation
    - vec3 mScale
    - Entity mParent
    - Container<Entity> mChildren
    - bool dirtyFlag
}
class Renderable <<Component>> {
    - ResourceHandle<MeshResource> mMeshHandle
    - ResourceHandle<MaterialResource> mMaterialHandle
}
class CameraManager extends BaseComponentsManager {
    entity的相机数据管理
    ==
    + Entity create()
    + Camera* getInstance(Entity e)
    + bool hasInstance(Entity e)
    + void destroy(Entity e)

    - SoaContainer<Entity, Camera> mCameras
}

class Camera <<Component>> {
    - ProjectionType mProjType
    - float zNear
    - float zFar
    - float mHFov
    - float mAspectRatio
}

class View {
    场景中的视图: 定义在场景的哪里看，怎么看
    ==
    --
    - String mName
    - Viewport mViewport
    - Entity mMainCamera
    - Scene* mScene
}

class Viewport {
    视口：定义视图里看哪里，多大范围
    ==
    --
    - float x
    - float y
    - float width
    - float height
}

SceneManager *-- Scene
Scene "1"o--"n" Entity
Scene "1" o--"n" View
EntityManager "1"*--"n" Entity
TransformManager "1"*--"n" Transform
RenderableManager "1"*--"n" Renderable
CameraManager "1"*--"n" Camera
LightManager "1"*--"n" Light
Transform <.. Entity
Renderable <.. Entity
Camera <.. Entity
Light <.. Entity
View "1"*--"1" Viewport
View "1"o--"1" Camera
Scene <.. ISceneDescriptor
....

=== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescriptor as SD order 30
participant SceneManager as SM order 40
participant EntityManager as EM order 50
participant TransformManager as TM order 60
participant RenderableManager as RM order 70
participant CameraManager as CM order 90
participant LightManager as LM order 100
participant Scene as Scene order 110
participant View as View order 120
User -> Engine++: 创建并初始化
Engine -> SM: new
SM -> Scene++: new
SM -> EM++: new
SM -> TM++: new
SM -> RM++: new
SM -> CM++: new
SM -> LM++: new
User -> SD: 派生并实现
User -> Engine: loadScene()
Engine -> SM: loadScene()
SM -> SM: resetScene()
SM -> SD: onLoad()
group 加载场景
    SD -> SM: createView()
    SM -> View++: new
    SM <- View: view
    SD -> EM: create()
    SD <-- EM: entity
    SD -> TM: create(entity)
    SD <- TM: transform
    ... 在其他Manager中创建entity对应的数据, 方法同上 ...
    SD -> Scene: addEntity(entity)
    SD -> SD: 配置view, scene, camera等关系
end
SM -> Engine: 完成场景加载
... main loop ...
Engine -> Engine: main loop退出
group 卸载场景
    Engine -> SM: unloadScene()
    SM -> SD: onUnload()
    SD -> SD: 自定义场景卸载逻辑
    SM -> SM: clearScene()
    Engine <- SM: 场景数据清理完毕
    Engine -> Engine: ResourceManager::clearAll()
end
....

此处渲染时场景读取的调用链暂略，详见渲染模块设计

== 渲染模块

=== 职责

. 根据场景描述收集渲染数据, 裁剪出需要渲染的部分
. 请求资源系统确保所需资源可用
. 描述渲染的流程(render pass及其组合)，渲染的方式(forward/deferred shading), 渲染的技术(PBR)
. 构建并管理每帧数据
. 根据pass生成render graph, 自动优化和确保同步机制，给出pass和资源的依赖关系，推导资源生命周期，按顺序执行
. 生成并录制渲染命令，提交到渲染底层(RHI)
. 界面绘制，后处理特效，及其他相关功能
. 渲染相关的多线程任务调度

=== 功能

. render pass
. render graph
. custom & flexible shading path(deferred/forward)
. pbr， ibl, directional shadow, tonemap

=== 边界

. 本版暂不集成job system
. 暂不做多线程命令录制
. 不直接操作和接触RM和RHI层的资源，只描述操作过程
. 以实现功能为主，设计上采用数据驱动和自动rg，架构上会预留扩展空间，但暂不保证测试覆盖，和性能

=== 设计思路

. 以render pass描述pass，可以通过render graph组织依赖关系，优化执行顺序，优化资源读写
. render graph支持自动屏障插入，不需要手动管理pass之间的依赖和操作同步原语
. renderer不会去直接与底层资源和内存资源交互，而是通过handle
. renderer带有自己的内存管理器，主要用于管理帧内资源，实现高效分配和回收，保证内存局部性和连续性

=== 具体设计

渲染模块放在**rendering/**目录下

==== 核心类及成员

[plantuml]
....
class Renderer {
    + void renderFrame(View& view)
    - void beginFrame()
    - void endFrame()

    - ResourceManager& mResourceManager
    - FrameContext mFrameContext
    - Container<FrameData> mPerFrameData
    - RenderGraph mRenderGraph
    - Driver& mDriver
}
class Driver {
  + {abstract} void acquireNextFrame()
  + {abstract} void startCmdRecording()
  + {abstract} void endCmdRecording()
  + {abstract} void submitFrame()
  + {abstract} void presentFrame()
  + {abstract} void endFrame()
  + {abstract} HwTexture& createTexture(TextureResource& resource)
  + {abstract} HwBuffer& createBuffer(BufferResource& resource)
}
class RenderPass {
    + void inputResource(ResourceHandle handle)
    + void outputResource(ResourceHandle handle)
    + void execute()

    - Container<ResourceHandle> mInputs
    - Container<ResourceHandle> mOutputs

}
class RenderGraph{
    + void addPass(RenderPass&& pass)
    + void compile()
    + void execute()

    - Driver& mDriver
    - Container<ResourceNode::IdType> mExecutionOrder
}

Renderer o-- Driver
Renderer *-- RenderGraph
RenderGraph "1"*--"n" RenderPass
....

==== 核心调用链

[plantuml]
....
actor developer as User order 10
participant Engine as Engine order 20
participant SceneDescriptor as SD order 30
participant Renderer as Renderer order 40
participant RenderGraph as RG order 42
participant Driver as Driver order 50
participant Scene as Scene order 60
participant View as View order 70

User -> Engine++: initialize()
Engine -> Driver++: new
Engine -> Renderer++: new
Renderer -> RG++: new
Engine -> Scene++: new
Engine -> View++: new
User -> Engine: loadScene()
Engine -> SD++: new
User -> Engine: run()
Engine -> SD: onLoad()
SD -> Scene: 重置并准备场景数据
SD -> View: 重置并准备视图，相机配置
group mainLoop
    Engine -> Renderer: beginFrame()
    Renderer -> Driver:  acquireNextFrame()
    Renderer <-- Driver: finish frame data update and syncing
    Engine <-- Renderer
    Engine -> View: update()
    Engine -> Scene: update()
    Engine -> Renderer: renderFrame()
    Renderer -> Renderer: View, Scene数据剔除，抽取, 写到PerFrameData
    Renderer -> RG: reset()
    Renderer -> RG: addPass()
    Renderer -> RG: compile()
    Renderer -> RG: execute()
    Engine <-- Renderer
Engine -> Renderer: endFrame()
Renderer -> Driver: submitFrame()
Renderer -> Driver: presentFrame()
Renderer -> Driver: endFrame()
end
....

== RHI模块

=== 职责

. 向渲染层提供统一的API，使其能操作backend资源
. 将接口调用映射到具体图形API实现
. 可描述，管理，操作backend的GPU资源
. 可完整支持并隔离上层渲染操作

=== 功能

. rhi接口
. rhi各种资源抽象
. rhi句柄

=== 边界

. 不实现多backend，只实现vulkan backend
. 暂不实现完整RHI， 只支持引擎需要的功能

=== 具体设计

==== 核心类及成员

==== 核心调用链

== vulkan后端

=== 职责

. 具体执行渲染绘制指令
. 对底层资源进行生命周期管理
. 对底层操作进行便利封装
. 继承RHI接口并提供实际功能实现

=== 功能

. 支持执行各种绘制指令
. 基础vulkan功能运行正常，功能点可扩展
. 资源和同步管理

=== 边界

. 主要保证渲染层需要的能力，暂不做高度优化

=== 具体设计

