= 模块设计简述

== core模块

=== memory

memory类负责引擎底层内存管理相关功能，基于模板策略实现了内存灵活的分配，调试，线程安全，对齐相关功能,方便兼容各种core库甚至stl的分配器，策略本身具备扩展性，可以扩展更多的分配算法和内存资源

== 资产/资源管理模块

资源管理可以说是整个引擎的大动脉，是必须清晰整理数据流，逻辑流，状态流的模块

=== 职责

. 从硬盘里读取文件，解析，转换，生成引擎内部资产
. 在引擎运行时，使用这些数据进行处理和渲染

=== 功能

. 文件读取和解析: 应包括gltf2.0形式的文件和ktx纹理文件，解析为对应数据结构
.. 复合资产文件：比如gltf解析，并分解成单个资产，比如material, mesh, texture, buffer, scene等
. 文件转换
.. 优化数据结构：比如mesh, texture，buffer等，在转换时可以优化为引擎内部字节流
.. 把gltf和ktx转为引擎内部的PdMesh, PdTexture, PdSceneGraph, PdBuffer等数据结构
. 运行时加载和资源生命周期管理: 把上述引擎内数据在引擎运行时加载到内存和GPU并控制其构造和销毁时机

=== 本版边界

. 实现gltf和ktx的读取，解析，转换，运行时加载，正确渲染
. 不实现gltf的蒙皮，动作，多场景解析
. 不实现异步多线程加载,但是预留扩展性
. 不实现流式加载，热重载，但是预留扩展性
. 不实现gltf导出，修改

=== 设计思路

. 资源的加载整体上分为两块，资产管理和资源管理,此处分别称为(Asset Management(AM)和Resource Management(RM))
.. AM: 负责硬盘文件信息读取，并解析转换为运行时资源信息，本身不负责直接加载数据，只解析和转换相关文件的信息，并提供把转换好的资产"注册"到运行时资源管理中
.. RM: 利用资产管理解析的文件信息，在运行时按照场景需要，把相关资产加载到内存或显存中，供引擎使用，并管理这些资源的生命周期

=== 具体设计

分为两个子模块:

. **asset/**: 资产管理相关功能,负责文件信息解析和转换
.. 根据文件格式不同，使用不同的parsers进行解析和转换，输出Asset类型的数据格式
.. asset拥有者为AM, AM管理Asset生命周期，外部只能使用不能自行创建和销毁
. **resource/**: 运行时资源管理功能，负责把转换后的引擎内部文件信息(Asset中的具体的单个资源)按需加载和销毁
.. 在场景加载时，根据场景需要的具体资产，在渲染过程中上传到显存中

==== 类设计

核心类与核心成员及其关系如下:

[plantuml]
....
class AssetManager {
    + Asset* createAsset(AssetCreateInfo info)
    + void destroyAsset(Asset* asset)
}
class Asset {
    - String mId
    - Container<Entity> mScenGraphEntities
    - Container<TextureHandle> mTextures
    - Container<MeshHandle> mMeshes
    - Container<MaterialHandle> mMaterials
}
Interface Parser {
    + {abstract} void parse(Asset& asset)
}
class GltfParser implements Parser {
    + void parse(Asset& asset)
}
class ResourceEntry {
    + Resource* pResource
    + uint32_t refCount
    + bool gcFlag
}
class ResourceManager{
    + ResourceHandle registerResource(Resource&& resource)
    + void unregisterResource(ResourceHandle handle)
    + void load(ResourceHandle handle)
    + void gc()
    + void clearAll()

    - Container<ResourceId, ResourceEntry> mRegistry

    - ResourceId generateId()
}
Interface Resource {
    + {abstract} void load()
    + {abstract} void unload()
    + Status status()

    - Status mStatus
}
class TextureResource implements Resource {
    + void load()
    + void unload()

    - RhiHandle<Texture> mRhiTexture
}
class Primitive {
    - RhiHandle<Buffer> mVertexBuffer
    - RhiHandle<Buffer> mIndexBuffer
    - MaterialHandle mMaterial
}
class MeshResource implements Resource {
    + void load()
    + void unload()
    
    - Container<Primitive> mPrimitives
}
class MaterialResource implements Resource {
    + void load()
    + void unload()

    - RhiHandle<DescriptorSet> mDescriptorSet
    - TextureHandle mBaseColor
    - TextureHandle mNormal
}
class Handle {
    - uint32_t mId
    - uint32_t mGeneration
}
class ResourceHandle<? extends Resource> extends Handle {
    - String name
}

AssetManager "1"*--"n" Asset
AssetManager "1"*--"n" Parser
Asset "1"o--"n" ResourceHandle
ResourceManager "1"*--"n" ResourceEntry
ResourceEntry "1"*--"1" Resource
ResourceManager "1"*--"n" ResourceHandle
Resource "1"<--"n" ResourceHandle
MeshResource "1"*--"n" Primitive
Primitive "1"o--"1" MaterialResource
MaterialResource "1"o--"n" TextureResource
....

==== 核心调用链

==== 资源创建

[plantuml]
....
participant Participant as Foo
actor       Actor       as Foo1
boundary    Boundary    as Foo2
control     Control     as Foo3
entity      Entity      as Foo4
database    Database    as Foo5
collections Collections as Foo6
queue       Queue       as Foo7
Foo -> Foo1 : To actor 
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7: To queue
....

==== 资源加载

==== 资源销毁

=== 测试

. 测试文件信息正确读取并解析成对应数据钢结构，见test/test_asset.cpp
. 测试把Asset注册到resource manager,并在运行时正确加载到内存中
.. 注：GPU资源上传相关功能暂不测试，会在其他模块中一起测试

== 场景管理模块

== 图形后端(底层渲染)模块

== 渲染模块
