= 系统设计

此为第一版设计，主要考虑的是系统整体设计合理，保证设计目标达成，功能正常运行，并预留扩展和优化空间

== 项目整体结构

* **docs**: 项目相关的文档记录，index.adoc是文档主入口
** doxygen: doxygen生成的源码文档
* **assets**: 通用资产
** models: 模型文件
*** characters: 人物模型
**** player: 玩家模型
**** npc: npc模型
*** environment: 环境模型
**** indoor: 室内模型
**** outdoor: 室外模型
*** props: 其他小物件
** textures: 纹理文件
** shaders: 着色器文件
*** core: 核心着色器
*** effect: 效果相关着色器
* **cmake**: cmake公共配置项
* **vcpkg**: vcpkg配置项
* **engine**: 引擎主目录
** config: 引擎配置
** source: 引擎源码
** vendor: 需要定制的三方库代码
* **samples**: 引擎使用样例
* **libs**: 引擎无关或依赖引擎的库

== 模块结构

引擎模块皆在engine/source下,其中include是公开的头文件, src是私有的头文件及cpp文件，test是单元测试代码。引擎代码皆在"pd"命名空间内，引擎内的模块划分如下:

* **platform**: 对应平台层: 包含操作系统相关操作，窗口系统封装等
* **core**: 对应核心层: 包含系统级基类，基础工具模块，全局配置等
* **backend**: 对应渲染(后端): RHI及其具体实现，图形API封装
* **rendering**: 对应渲染(前端)：包含渲染器，render graph, 材质系统，特效等具体的渲染功能
* **asset**: 对应资产层: 包括资产文件读取，解析，转换相关功能，主要是运行前的资产(prefab)转换为统一的引擎内部数据的处理工作，目前属于引擎的一部分，没有独立为转换器
* **resource**: 对应资源层: 包含运行时的资源定义，句柄管理，资源管理等资源功能，并且控制backend底层资源的实际加载过程
* **scene**: 对应场景层：包含场景定义，视图, 场景数据管理等功能

其中应用层主要通过libs/application模块实现，因其只依赖整个引擎，故可以独立于引擎的核心代码

== 引擎整体设计

* 以接口定义契约，接口采用纯接口类，不使用抽象类
* Engine只是一个薄的大容器，没有具体执行逻辑，只负责子系统的停启，子系统负责具体职责内逻辑，不依赖Engine
* 子系统之间使用接口建立依赖关系，核心骨架调用为命令式显式调用，其他跨子系统的调用通过事件模式解耦
* 全局禁用异常，非热路径采用std::expected + noexcept声明函数
* 使用RAII管理资源，使用handle引用资源，handle根据生命周期和范围分为多种类型，一般由manager统一管理生命周期，暂无ABI和接口化需求，故不做pimpl和动态链接
* 分模块的设计和开发策略，主要根据模块本身的功能需求和性能需求决定，详见模块设计

线程有三个主要线程:

* 主线程(逻辑线程): 负责监控和协调引擎整体的状态，子系统状态，引擎的停启
* 渲染线程: 负责渲染相关事务执行
* 作业系统工作线程池: 负责资产处理，资源加载，场景数据处理等异步任务

核心类结构及关系如下：

[NOTE]
====
* 此处只展示整体代码框架，包含核心成员和类层级及其关系，具体成员和函数见模块设计
* 具体技术细节此阶段不考虑，详见模块设计
====

[plantuml]
....
class Application {
    封装引擎调用以方便用户使用,加载默认配置和常用资源
    ==
    - Engine mEngine
}

class Engine {
    协调子系统运行, 提供操作接口，尽量轻，不负责具体逻辑
    ==
    - IPlatform* mPlatform
    - IBackend* mBackend
    - ResourceManager mResourceManager
    - AssetManager mAssetManager
    - SceneManager mSceneManager
    - Renderer mRenderer
}
class AssetManager {
    离线资源加载，转换
    ==
}
class ResourceManager {
    运行时资源管理
    ==
}
class SceneManager {
    场景管理器：负责场景相关数据统一处理，场景描述，场景
    ==
    - Scene mScene
    - Container<View> mViews
}
Interface IPlatform {
    平台隔离接口,非虚
    ==
}
Interface IFileSystem{
    文件系统接口,虚
    ==
}
class StdFileSystem implements IFileSystem {
    std实现的文件系统
    ==
}
class PlatformWin32 implements IPlatform {
    windows平台实现
    ==
    - IFileSystem* mFileSystem
    - IWIndow* mWindow
}
Interface IWindow {
    窗口系统接口
    ==
}
class WindowSDL3 implements IWindow {
    SDL3窗口系统
    ==
}
Interface IBackend {
    渲染后端(图形API)接口,非虚
    ==
}
class BackendVulkan implements IBackend {
    vulkan后端实现
    ==
}
class Renderer {
    渲染器: 指定渲染流程，构建RG,调用渲染后端执行绘制
    ==
}
class Scene {
    场景描述和相关数据
    ==
}
class View {
    视图：决定在场景中如何看，怎么看
    ==
    - Camera mMainCamera
}

Application *-- Engine
Engine *-- IPlatform
Engine *-- IBackend
Engine *-- Renderer
Engine *-- SceneManager
SceneManager "1"*--"1" Scene
SceneManager "1"*--"n" View
SceneManager o-- ResourceManager
SceneManager o-- AssetManager
IPlatform *-- IWindow
IPlatform *-- IFileSystem
Engine *-- AssetManager
Engine *-- ResourceManager
Scene "1"o--"n" View
Renderer o-- IBackend
Renderer o-- View
IWindow <.. IBackend
....

根据此代码框架，拆分出粗粒度的模块设计工作：

. Engine/Core模块设计
. Platform模块设计
. Resource模块设计
. Asset模块设计
. Scene模块设计
. Backend模块设计
. Vulkan模块设计
. App模块设计

每个模块的具体设计详见模块设计

=== 开发策略

. 代码风格和规范参考clang-format和tidy配置，基本上可参考google代码风格，代码规范和建议主要参考{cpp} core guideline
. 对于非热点数据的分配，优先用栈，使用堆时，帧外，非热路径调用，可用STL，帧内，或热路径，需要通过Arena分配

== 开发边界

. 不考虑严封装，故对用户开放的控制权限过大，是因为减轻设计和实现成本，依赖用户自律
. 动态链接，插件系统，脚本系统，接口化(pimpl)等视作后期扩展功能，此阶段暂时不实现