= 系统设计

此为第一版设计，主要考虑的是系统整体设计合理，保证设计目标达成，功能正常运行，并预留扩展和优化空间

== 项目整体结构

* **docs**: 项目相关的文档记录，index.adoc是文档主入口
** doxygen: doxygen生成的源码文档
* **assets**: 项目资产
** models: 模型文件
*** characters: 人物模型
**** player: 玩家模型
**** npc: npc模型
*** environment: 环境模型
**** indoor: 室内模型
**** outdoor: 室外模型
*** props: 其他小物件
** textures: 纹理文件
** shaders: 着色器文件
*** core: 核心着色器
*** effect: 效果相关着色器
* **cmake**: cmake公共配置项
* **vcpkg**: vcpkg配置项
* **engine**: 引擎主目录
** config: 引擎配置
** source: 引擎源码
* **samples**: 引擎使用案例
* **libs**: 引擎无关或依赖引擎的库

== 模块结构

引擎模块皆在engine/source下,其中include是公开的头文件, src是私有的头文件及cpp文件，test是单元测试代码。引擎代码皆在"pd"命名空间内，模块以文件夹区分而不再嵌套命名空间以维持扁平简单的结构，引擎内的模块划分如下:

* **platform**: 对应平台层: 包含操作系统相关操作，RHI, 渲染后端底层API封装，窗口系统封装等
* **core**: 对应核心层: 包含系统级基类，基础工具模块，基础功能等
* **asset**: 对应资产层: 包括资产文件读取，解析，转换相关功能
* **resource**: 对应资源层: 包含资源定义，句柄，资源管理器，资源加载器等资源相关类
* **rendering**: 对应渲染层：包含渲染器，pass定义，render graph, 材质模块等基础渲染相关类
* **scene**: 对应场景层： 包含场景定义，场景视图, 场景相关工具类等

其中应用层主要通过libs/application模块实现，因其只依赖整个引擎，故可以独立出引擎的核心代码

== 引擎整体设计

* 以接口定义契约，接口采用纯接口类，不使用抽象类
* Engine只是一个薄的大容器，没有具体执行逻辑，只负责子系统的停启，子系统负责具体职责内逻辑，不依赖Engine，使用接口建立依赖关系
* 跨子系统的调用需求通过事件模式解耦并实现
* 全局禁用异常，非热路径采用std::expected + noexcept声明函数
* 使用RAII管理资源
* 分模块，并根据性能要求决定设计和开发策略，详见模块设计

线程有三个主要线程:

* 主线程(逻辑线程): 负责监控引擎整体的状态，子系统状态，引擎的停启
* 渲染线程: 负责渲染事务执行
* 资源线程: 负责资源加载

核心类结构及关系如下：

[plantuml]
....
class Application {
    封装引擎调用以方便用户使用,加载默认配置和常用资源
    ==
}

class Engine {
    协调子系统运行, 提供操作接口，尽量轻，不负责具体逻辑
    ==
    - Container<ILayer*> mLayers
    - IPlatform* mPlatform
    - IBackend* mBackend
    - ResourceManager mResourceManager
    - AssetManager mAssetManager
    - Scene mScene
    - Container<View*> mViews
    - Renderer mRenderer
}
Interface ILayer {
    界面分层接口
    ==
}
class GuiLayer implements ILayer{
    菜单界面
    ==
}
class AssetManager {
    离线资源加载，转换
    ==
}
class ResourceManager {
    运行时资源管理
    ==
}
Interface IPlatform {
    平台隔离接口
    ==
}
Interface IFileSystem{
    文件系统接口
    ==
}
class StdFileSystem implements IFileSystem {
    std实现的文件系统
    ==
}
class PlatformWin32 implements IPlatform {
    windows平台实现
    ==
    - IFileSystem* mFileSystem
    - IWIndow* mWindow
}
Interface IWindow {
    窗口系统接口
    ==
}
class WindowSDL3 implements IWindow {
    SDL3窗口系统
    ==
}
class WindowWin32 implements IWindow {
    windows原生窗口系统
    ==
}
Interface IBackend {
    渲染后端(图形API)接口
    ==
}
class BackendVulkan implements IBackend {
    vulkan后端实现
    ==
}
class Renderer {
    渲染器: 指定渲染流程，构建RG,调用渲染后端执行绘制
    ==
}
class Scene {
    场景描述和相关数据
    ==
}
class View {
    视图：决定在场景中如何看，怎么看
    ==
}

Application *-- Engine
Engine *-- IPlatform
Engine *-- IBackend
Engine *-- Renderer
Engine *-- Scene
Engine "1"*--"n" ILayer
Engine "1"*--"n" View
IPlatform *-- IWindow
IPlatform *-- IFileSystem
Engine *-- AssetManager
Engine *-- ResourceManager
Scene "1"o--"n" View
Renderer o-- IBackend
Renderer o-- View
IWindow <.. IBackend
....

根据整体类图，拆分出模块设计工作：

. Engine/Core模块设计
. Resource模块设计
. Platform模块设计
. Vulkan模块设计
. Asset模块设计
. Scene/View模块设计
. Backend模块设计
. App模块设计

每个模块的具体设计详见模块设计

=== 使用策略

. 全局禁用异常，对帧外逻辑采用std::expected + noexcept声明， 每层按需自行构造强类型枚举错误码
. 对于引擎内部的数据结构和基础类，使用核心库的STL
. 对于非热点数据的分配，优先用栈，使用堆时，需要通过Arena分配，不允许使用C/{cpp}自己的分配/销毁操作
. 对于热点数据，使用Arena并选用合适的分配策略，如Pool, Linear等

== 系统全局规约

. 代码风格和规范参考clang-format和tidy配置，基本上可参考google代码风格，代码质量主要参考{cpp} core guideline
. 引擎代码不允许使用{cpp} exception, 用错误码，bool取代


== 已知问题

. 对用户开放的控制权限过大，暂时不严格封装，是因为减轻设计和实现成本，依赖用户自律，用户操作目前可控
. 无ABI稳定支持，pimpl之类，暂时不实现，后期若需要可在上层加API层封装