= 系统设计

此为第一版设计，主要考虑的是系统整体设计合理，保证设计目标达成，功能正常运行，并预留扩展和优化空间

== 项目整体结构

* **docs**: 项目相关的文档记录，index.adoc是文档主入口
** doxygen: doxygen生成的源码文档
* **assets**: 通用资产
** models: 模型文件
*** characters: 人物模型
**** player: 玩家模型
**** npc: npc模型
*** environment: 环境模型
**** indoor: 室内模型
**** outdoor: 室外模型
*** props: 其他小物件
** textures: 纹理文件
** shaders: 着色器文件
*** core: 核心着色器
*** effect: 效果相关着色器
* **cmake**: cmake公共配置项
* **vcpkg**: vcpkg配置项
* **engine**: 引擎主目录
** config: 引擎配置
** source: 引擎源码
** vendor: 需要定制的三方库代码
* **samples**: 引擎使用样例
* **libs**: 引擎无关或依赖引擎的库

== 模块结构

引擎模块皆在engine/source下,其中include是公开的头文件, src是私有的头文件及cpp文件，test是单元测试代码。引擎代码皆在"pd"命名空间内，引擎内的模块划分如下:

* **platform**: 对应平台层: 包含操作系统相关操作，窗口系统封装等
** window system: 窗口系统：对各个平台及跨平台窗口系统进行封装，可在构建时选择
** file system: 文件系统: 对各个平台和设备提供文件系统抽象
* **core**: 对应核心层: 包含系统级基类，基础工具模块，全局配置等
** utils: 引擎无关的工具库
** math: 数学库
* **backend**: 对应渲染(后端): RHI及其具体实现，图形API封装
** vulkan: vulkan底层封装
* **rendering**: 对应渲染(前端)：包含渲染器，render graph, 材质系统，特效等具体的渲染功能
** render graph: 渲染图实现
** material: 材质系统实现
* **asset**: 对应资产层: 包括资产文件读取，解析，转换相关功能，主要是运行前的资产(prefab)转换为统一的引擎内部数据的处理工作
** parser: 资产文件解析器
* **resource**: 对应资源层: 包含运行时的资源定义，句柄管理，资源管理等资源功能，并且控制backend底层资源的实际加载过程
* **scene**: 对应场景层：包含场景定义，视图, 场景数据管理等功能

其中应用层主要通过libs/application模块实现，因其只依赖整个引擎，故可以独立于引擎的核心代码

== 引擎整体设计思路

* Engine只是一个薄的大容器，没有具体执行逻辑，只负责子系统的停启，和顶层协调骨架级逻辑，子系统负责具体职责内逻辑，不直接依赖Engine
* 核心骨架调用为命令式显式调用，其他跨子系统的调用通过事件模式解耦
* 全局禁用异常，非热路径采用std::expected + noexcept声明函数
* 底层资源使用RAII封装，使用handle引用资源，由resource manager统一管理生命周期
* 分模块的设计和开发策略，主要根据模块本身的功能需求和性能需求决定，详见模块设计

线程模型:

* 主线程(逻辑线程): 负责监控和协调引擎整体的状态，子系统状态，引擎的停启
* 渲染后端线程: 负责渲染底层相关事务执行
* job system: 负责资产处理，资源加载，场景数据,渲染任务等异步任务
* 渲染任务会通过jobsystem执行，把渲染指令存储到一个ring buffer里，由渲染后端线程从buffer中获取并执行

核心类结构及关系如下：

[NOTE]
====
* 此处只展示整体代码框架，包含核心成员和类层级及其关系，具体成员和函数见模块设计
* 具体技术细节此阶段不考虑，详见模块设计
====

[plantuml]
....
class Application {
    封装引擎调用以方便用户使用,加载默认配置和常用资源
    ==
    - Engine mEngine
}

class Engine {
    协调子系统运行, 提供操作接口，尽量轻，不负责具体逻辑
    ==
    - Platform mPlatform
    - Backend mBackend
    - ResourceManager mResourceManager
    - AssetManager mAssetManager
    - SceneManager mSceneManager
    - Renderer mRenderer
}
class AssetManager {
    离线资源加载，转换
    ==
}
class ResourceManager {
    运行时资源管理
    ==
}
class SceneManager {
    场景管理器：负责场景相关数据统一处理，场景描述，场景
    ==
    - Scene mScene
    - vector<View> mViews
}
Interface Platform {
    平台隔离接口, 编译期确定
    ==
}
Interface IFileSystem{
    文件系统接口,运行期多态
    ==
}
class StdFileSystem implements IFileSystem {
    std实现的文件系统
    ==
}
class PlatformWin32 implements Platform {
    windows平台实现
    ==
    - IFileSystem* mFileSystem
    - WindowSystem mWindow
}
Interface WindowSystem {
    窗口系统接口，编译期确定
    ==
}
class WindowSystemSDL3 implements WindowSystem {
    SDL3窗口系统
    ==
}
Interface Backend {
    渲染后端(图形API)接口, 编译期确定
    ==
}
class BackendVulkan implements Backend {
    vulkan后端实现
    ==
}
class Renderer {
    渲染器: 指定渲染流程，构建RG,调用渲染后端执行绘制
    ==
}
class Scene {
    场景描述和相关数据
    ==
}
class View {
    视图：决定在场景中如何看，怎么看
    ==
    - Camera mMainCamera
}

Application *-- Engine
Engine *-- Platform
Engine *-- Backend
Engine *-- Renderer
Engine *-- ResourceManager
Engine *-- AssetManager
Engine *-- SceneManager
PlatformWin32 *-- WindowSystem
PlatformWin32 *-- IFileSystem
ResourceManager o-- Backend
AssetManager o-- IFileSystem
SceneManager "1"*--"1" Scene
SceneManager "1"*--"n" View
SceneManager o-- ResourceManager
SceneManager o-- AssetManager
Scene "1"o--"n" View
Renderer o-- Backend
Renderer o-- SceneManager
WindowSystem <.. Backend
....

根据此代码框架，拆分出粗粒度的模块设计工作：

. Engine/Core模块设计
. Platform模块设计
. Resource模块设计
. Asset模块设计
. Scene模块设计
. Backend模块设计
. Vulkan模块设计
. App模块设计

每个模块的具体设计详见模块设计

=== 开发策略

. 代码风格和规范参考clang-format和tidy配置，基本上可参考google代码风格，代码规范和建议主要参考{cpp} core guideline
. 对于非热点数据的分配，优先用栈，使用堆时，帧外，非热路径调用，可用STL，帧内，或热路径，需要通过Arena分配

== 开发边界

. 插件系统，脚本系统，编辑器等视作后期扩展功能，此阶段暂时不实现