= 系统设计

此为第一版设计，主要考虑的是系统整体设计合理，保证设计目标达成，功能正常运行，并预留扩展和优化空间

== 项目整体结构

* **docs**: 项目相关的文档记录，index.adoc是文档主入口
** doxygen: doxygen生成的源码文档
* **assets**: 项目资产
** models: 模型文件
*** characters: 人物模型
**** player: 玩家模型
**** npc: npc模型
*** environment: 环境模型
**** indoor: 室内模型
**** outdoor: 室外模型
*** props: 其他小物件
** textures: 纹理文件
** shaders: 着色器文件
*** core: 核心着色器
*** effect: 效果相关着色器
* **cmake**: cmake公共配置项
* **vcpkg**: vcpkg配置项
* **engine**: 引擎主目录
** config: 引擎配置
** source: 引擎源码
* **samples**: 引擎使用案例
* **libs**: 引擎无关或依赖引擎的库

== 模块结构

引擎模块皆在engine/source下,其中include是公开的头文件, src是私有的头文件及cpp文件，test是单元测试代码。引擎代码皆在"pd"命名空间内，模块以文件夹区分而不再嵌套命名空间以维持扁平简单的结构，引擎内的模块划分如下:

* **platform**: 对应平台层: 包含操作系统相关操作，RHI, 渲染后端底层API封装，窗口系统封装等
* **core**: 对应核心层: 包含系统级基类，基础工具模块，基础功能等
* **asset**: 对应资产层: 包括资产文件读取，解析，转换相关功能
* **resource**: 对应资源层: 包含资源定义，句柄，资源管理器，资源加载器等资源相关类
* **rendering**: 对应渲染层：包含渲染器，pass定义，render graph, 材质模块，相机等基础渲染功能
* **scene**: 对应场景层： 包含场景定义，场景视图, 场景相关工具类等

其中应用层主要通过libs/application模块实现，因其只依赖整个引擎，故可以独立出引擎的核心代码

== 引擎整体设计

每一层可看作一个子系统，由Engine类作为入口，Engine负责各个子系统的停启，只在启动和销毁时有逻辑，其余时间只负责监控和协调各个子系统的运行情况，其次，用于暴露引擎内部操作和内部资源相关的接口

Engine启动顺序按照层级依赖关系依次进行，其本身不属于某个模块，故直接放在头文件的根目录下

线程有两个主要线程:

* 主线程: 负责监控引擎整体的状态，子系统状态，引擎的停启
* 渲染线程: 负责渲染事物执行

核心类结构及关系如下：

[plantuml]
....
class Application {
}
note top of Application : 封装引擎调用以方便用户使用,加载默认配置和常用资源
class Engine {
}
note top of Engine : 子系统停启，监控
class ResourceManager {}
note top of ResourceManager : 资源加载，管理
Interface Platform {
}
note top of Platform : 平台层抽象，跨平台预留
class PlatformWindows{}
note top of PlatformWindows : Windows平台相关功能实现
Interface Window {
}
note top of Window : 窗口系统接口
class Sdl3Window {
}
note top of Sdl3Window : SDL3窗口系统实现
Interface Driver {}
note top of Driver : 渲染后端API接口(RHI), 预留
class VulkanDriver {
}
note top of VulkanDriver : Vulkan后端封装
class Renderer {
}
note top of Renderer : 渲染子系统，负责执行具体的渲染逻辑
class Scene {
}
note top of Scene : 场景描述，比如光线，物件，变换，剔除等
class View {
}
note top of View : 场景中的视窗，包括视锥体，相机，渲染参数等

Application "1" -->"1" Engine
Application o-- Scene
Application o-- Renderer
Engine *-- Platform
Engine *-- ResourceManager
Engine "1"*--"1" Renderer
Engine "1"*--"n" Scene
Engine "1"*--"n" View
Platform <|-- PlatformWindows
PlatformWindows "1"*--"1" Driver
PlatformWindows "1"*--"1" Window
Window <|.. Sdl3Window
Driver <|.. VulkanDriver
Scene "1"o--"n" View
Driver <-- Renderer
Window <-- Renderer
View "n"<--"1" Renderer
ResourceManager <-- Renderer
....

== 内存管理

由于引擎对内存分配策略需求多样且极度敏感，并且需要对接标准库，结论简要概述如下:

. 采用自研Arena负责控制内存分配，满足通用堆分配，内存池，线性分配器，内存对齐的需求
. 引擎内部的通用功能部分，使用{cpp}的STL实现，对于帧内和热路径和数据，采用自实现核心库
.. STL的内存分配，非必要不使用自定义分配器
. 使用TLSF作为内存池实现，每个Arena实例独立拥有一个池，支持对齐，每次分配使用锁保证线程安全
.. 注意点:
... 每个池需要预留空间给tlsf记录分配信息,有额外内存开销，故适用于大于1M的内存池
... 目前主要考虑x86架构，其他平台暂不考虑

=== 使用策略

. 全局禁用异常，对帧外逻辑采用std::expected + noexcept声明， 每层按需自行构造强类型枚举错误码
. 对于引擎内部的数据结构和基础类，使用核心库的STL
. 对于非热点数据的分配，优先用栈，使用堆时，需要通过Arena分配，不允许使用C/{cpp}自己的分配/销毁操作
. 对于热点数据，使用Arena并选用合适的分配策略，如Pool, Linear等

== 线程模型

目前分为主线程和渲染线程，在执行每帧逻辑时，使用job system执行场景数据处理，然后会把渲染指令录制下来，通过ringbuffer并提交给渲染线程执行

== 系统全局规约

. 代码风格和规范参考clang-format和tidy配置，基本上可参考google代码风格，代码质量主要参考{cpp} core guideline
. 引擎代码不允许使用{cpp} exception, 用错误码，bool取代

== 模块设计简述

为减少文档工作，在此只简述模块设计和实现思路，详见doxygen文档和代码


== 已知问题

. 对用户开放的控制权限过大，暂时不严格封装，是因为减轻设计和实现成本，依赖用户自律，用户操作目前可控
. 无ABI稳定支持，pimpl之类，暂时不实现，后期若需要可在上层加API层封装